// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Talkif from "../../../index.js";

export declare namespace BillingClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Balance management, payment methods, charges, and pricing
 */
export class BillingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BillingClient.Options>;

    constructor(options: BillingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * GET /api/v1/billing/balances
     *
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getBalanceSummary()
     */
    public getBalanceSummary(
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.BalanceSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getBalanceSummary(requestOptions));
    }

    private async __getBalanceSummary(
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.BalanceSummaryResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/billing/balance",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.BalanceSummaryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/billing/balance");
    }

    /**
     * Paginated, filterable charge history for an account.
     * Returns charges with entity context (phone number, flow name, contact name)
     * from the first associated cost line item.
     *
     * @param {Talkif.ListChargesRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.listCharges()
     */
    public listCharges(
        request: Talkif.ListChargesRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.ChargeListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listCharges(request, requestOptions));
    }

    private async __listCharges(
        request: Talkif.ListChargesRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.ChargeListResponse>> {
        const { limit, offset, charge_type: chargeType, status, start_date: startDate, end_date: endDate } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            charge_type: chargeType != null ? chargeType : undefined,
            status: status != null ? status : undefined,
            start_date: startDate,
            end_date: endDate,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/billing/charges",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.ChargeListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/billing/charges");
    }

    /**
     * Detailed charge view with cost line items breakdown.
     *
     * @param {Talkif.GetChargeDetailRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getChargeDetail({
     *         chargeId: "chargeId"
     *     })
     */
    public getChargeDetail(
        request: Talkif.GetChargeDetailRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.ChargeDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getChargeDetail(request, requestOptions));
    }

    private async __getChargeDetail(
        request: Talkif.GetChargeDetailRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.ChargeDetailResponse>> {
        const { chargeId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/billing/charges/${core.url.encodePathParam(chargeId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.ChargeDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/billing/charges/{chargeId}",
        );
    }

    /**
     * Get account-level cost breakdown by category with drill-down to calls.
     *
     * ## Query Parameters
     * - `period`: `today`, `week`, `month`, or `custom` (default: `week`)
     * - `startDate`: Required when `period=custom`
     * - `endDate`: Required when `period=custom`
     *
     * ## Response
     * Returns total costs, breakdown by category (LLM, STT, TTS, telephony),
     * breakdown by flow, and recent calls with individual cost breakdowns.
     *
     * @param {Talkif.GetBillingCostBreakdownRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getBillingCostBreakdown()
     */
    public getBillingCostBreakdown(
        request: Talkif.GetBillingCostBreakdownRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.AnalyticsCostBreakdownResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getBillingCostBreakdown(request, requestOptions));
    }

    private async __getBillingCostBreakdown(
        request: Talkif.GetBillingCostBreakdownRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.AnalyticsCostBreakdownResponse>> {
        const { period, startDate, endDate } = request;
        const _queryParams: Record<string, unknown> = {
            period,
            startDate,
            endDate,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/billing/costs",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Talkif.AnalyticsCostBreakdownResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/billing/costs");
    }

    /**
     * Get detailed cost breakdown for a single call with line items.
     *
     * Returns all cost line items including usage data (tokens, seconds, characters)
     * and rate information for each cost component.
     *
     * @param {Talkif.GetBillingCallCostBreakdownRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getBillingCallCostBreakdown({
     *         callId: "callId"
     *     })
     */
    public getBillingCallCostBreakdown(
        request: Talkif.GetBillingCallCostBreakdownRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.CallCostBreakdownResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getBillingCallCostBreakdown(request, requestOptions));
    }

    private async __getBillingCallCostBreakdown(
        request: Talkif.GetBillingCallCostBreakdownRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.CallCostBreakdownResponse>> {
        const { callId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/billing/costs/calls/${core.url.encodePathParam(callId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.CallCostBreakdownResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/billing/costs/calls/{callId}",
        );
    }

    /**
     * GET /api/v1/billing/invoices
     *
     * @param {Talkif.ListInvoicesRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.listInvoices()
     */
    public listInvoices(
        request: Talkif.ListInvoicesRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.InvoiceListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listInvoices(request, requestOptions));
    }

    private async __listInvoices(
        request: Talkif.ListInvoicesRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.InvoiceListResponse>> {
        const { limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/billing/invoices",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.InvoiceListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/billing/invoices");
    }

    /**
     * GET /api/v1/billing/invoices/{invoiceId}
     *
     * @param {Talkif.GetInvoiceRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getInvoice({
     *         invoiceId: "invoiceId"
     *     })
     */
    public getInvoice(
        request: Talkif.GetInvoiceRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.InvoiceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getInvoice(request, requestOptions));
    }

    private async __getInvoice(
        request: Talkif.GetInvoiceRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.InvoiceResponse>> {
        const { invoiceId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/billing/invoices/${core.url.encodePathParam(invoiceId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.InvoiceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/billing/invoices/{invoiceId}",
        );
    }

    /**
     * GET /api/v1/billing/transactions
     *
     * @param {Talkif.GetTransactionHistoryRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getTransactionHistory()
     */
    public getTransactionHistory(
        request: Talkif.GetTransactionHistoryRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.BalanceTransactionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTransactionHistory(request, requestOptions));
    }

    private async __getTransactionHistory(
        request: Talkif.GetTransactionHistoryRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.BalanceTransactionListResponse>> {
        const { limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/billing/transactions",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Talkif.BalanceTransactionListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/billing/transactions");
    }

    /**
     * Public endpoint — no authentication required.
     * Returns telephony rates, phone number pricing, and recording storage pricing.
     *
     * LLM/STT/TTS pricing is served by `GET /api/v1/models/*` with richer data
     * (capabilities, languages, use-case filtering).
     *
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.billing.getPublicPricing()
     */
    public getPublicPricing(
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PublicPricingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPublicPricing(requestOptions));
    }

    private async __getPublicPricing(
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PublicPricingResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/pricing",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PublicPricingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.TalkifError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/pricing");
    }
}
