// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumbers: ["+15551234567", "+15559876543"]
 *     }
 */
export interface CheckDncRequest {
    /** Phone numbers to check in E.164 format (1-100 numbers per request) */
    phoneNumbers: string[];
}
