// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         phoneNumber: "+15551234567"
 *     }
 */
export interface CreateDncEntryRequest {
    /** Phone number in E.164 format */
    phoneNumber: string;
    /** Human-readable reason for adding to DNC list (max 500 characters) */
    reason?: string | null;
    /** How this DNC entry was created (default: manual) */
    source?: Talkif.DncSource;
}
