// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListDncEntriesRequest {
    /** Max items to return (default: 20) */
    limit?: number;
    /** Items to skip */
    offset?: number;
    /** Filter by phone number (partial match) */
    search?: string;
    /** Filter by source (exact match) */
    source?: string;
}
