// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         campaignId: "campaignId",
 *         contactIds: ["contactIds"]
 *     }
 */
export interface AddCampaignContactsRequest {
    /** Campaign ID */
    campaignId: string;
    /** List of contact IDs to add (1-1000 per request) */
    contactIds: string[];
}
