// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         campaignId: "campaignId",
 *         filter: {}
 *     }
 */
export interface BulkAddContactsRequest {
    /** Campaign ID */
    campaignId: string;
    /** Filter criteria to select which contacts to add */
    filter: Talkif.BulkContactFilter;
}
