// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListCampaignsRequest {
    /** Filter by status */
    status?: Talkif.CampaignStatus;
    /** Case-insensitive search over name and description */
    search?: string;
    /** Max items to return */
    limit?: number;
    /** Items to skip */
    offset?: number;
}
