// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         campaignId: "campaignId"
 *     }
 */
export interface ListCampaignContactsRequest {
    /** Campaign ID */
    campaignId: string;
    /** Filter by derived contact status */
    status?: Talkif.CampaignContactStatus;
    /** Case-insensitive search over phone number, name and email */
    search?: string;
    /** Max items to return (1-100) */
    limit?: number;
    /** Items to skip */
    offset?: number;
}
