// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         campaignId: "campaignId"
 *     }
 */
export interface StartCampaignRequest {
    /** Campaign ID */
    campaignId: string;
}
