// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetBillingCostBreakdownRequest {
    /** Time period: today, week, month, or custom */
    period?: string;
    /** Start date for custom period */
    startDate?: string;
    /** End date for custom period */
    endDate?: string;
}
