// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         chargeId: "chargeId"
 *     }
 */
export interface GetChargeDetailRequest {
    /** Charge ID */
    chargeId: string;
}
