// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetTransactionHistoryRequest {
    /** Max items to return */
    limit?: number;
    /** Items to skip */
    offset?: number;
}
