// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         providerId: "providerId"
 *     }
 */
export interface ListAvailableCountriesRequest {
    /** Provider ID */
    providerId: string;
}
