// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "+15551234567",
 *         providerId: "550e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface PurchasePhoneNumberRequest {
    /** Optional friendly name for the number */
    friendlyName?: string | null;
    /** Phone number to purchase in E.164 format */
    phoneNumber: string;
    /** ID of the provider to purchase through */
    providerId: string;
}
