// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdatePhoneNumberRequest {
    /** Phone number ID */
    id: string;
    /** Updated friendly name for the number */
    friendlyName?: string | null;
    /** Recording override setting (e.g. "do-not-record", "record-from-answer") */
    recordingOverride?: string | null;
}
