// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTtsVoicesRequest {
    /** Page size (max 100, default 50) */
    pageSize?: number;
    /** Pagination token for next page */
    nextPageToken?: string;
    /** Search term */
    search?: string;
    /** Voice type filter (v2 API) */
    voiceType?: string;
    /** Category filter */
    category?: string;
    /** Gender filter (male, female, neutral) — shared-voices API */
    gender?: string;
    /** Age group filter (young, middle_aged, old) — shared-voices API */
    age?: string;
    /** Language filter (ISO code) — shared-voices API */
    language?: string;
    /** Accent filter — shared-voices API */
    accent?: string;
    /** Sort order (trending, latest, most_users) — shared-voices API */
    sort?: string;
    /** 0-based page offset — shared-voices API */
    page?: number;
}
