// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         scheduleId: "scheduleId"
 *     }
 */
export interface DeleteScheduleRequest {
    /** Schedule ID */
    scheduleId: string;
}
