// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Appointment Reminder"
 *     }
 */
export interface CreateFlowRequest {
    /** Custom analysis instructions appended to the base analysis prompt */
    analysisInstructions?: string | null;
    /** Call analysis behavior override: "use_account_default", "enabled", or "disabled" */
    analysisOverride?: string | null;
    definition?: Talkif.FlowDefinition | null;
    /** Description of the flow's purpose (max 1000 characters) */
    description?: string | null;
    /**
     * Visual builder layout (node positions, viewport). Opaque to the API.
     * When present it is stored as-is; when omitted, a default layout is
     * generated from the definition.
     */
    layout?: Record<string, unknown> | null;
    maxCallDuration?: Talkif.MaxCallDurationSettings | null;
    /** Display name of the flow (1-255 characters) */
    name: string;
    /** Recording behavior override: "use_account_default", "enabled", or "disabled" */
    recordingOverride?: string | null;
    userIdle?: Talkif.UserIdleSettings | null;
    /** Enable voicemail detection for this flow (outbound Twilio calls only) */
    voicemailEnabled?: boolean | null;
    /** Static voicemail message spoken verbatim (skips the composer LLM call) */
    voicemailMessage?: string | null;
    /** Instruction for composing the voicemail message (ignored if message is set) */
    voicemailMessagePrompt?: string | null;
    /** Seconds to wait after the callee stops speaking before leaving the message */
    voicemailResponseDelaySecs?: number | null;
}
