// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         flowId: "flowId"
 *     }
 */
export interface DeleteFlowRequest {
    /** Flow ID */
    flowId: string;
}
