// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListFlowsRequest {
    /** Max items to return (1-100, default 20) */
    limit?: number;
    /** Items to skip (default 0) */
    offset?: number;
}
