// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         flowId: "flowId"
 *     }
 */
export interface PublishFlowRequest {
    /** Flow ID */
    flowId: string;
    /** Expected current version for optimistic locking (rejects with 409 if stale) */
    expectedVersion?: string | null;
    /** Changelog notes describing what changed in this version (max 1000 characters) */
    notes?: string | null;
    /** Explicit version override in X.Y.Z format (auto-increments patch if omitted) */
    version?: string | null;
}
