// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         callId: "callId"
 *     }
 */
export interface GetCallStatusRequest {
    /** Call ID */
    callId: string;
}
