// This file was auto-generated by Fern from our API Definition.

/**
 * Response indicating how many contacts were added
 */
export interface AddedResponse {
    /** Number of contacts successfully added to the campaign */
    added: number;
}
