// This file was auto-generated by Fern from our API Definition.

/** Agent type discriminator */
export const AgentType = {
    MainAgent: "main_agent",
    Agent: "agent",
} as const;
export type AgentType = (typeof AgentType)[keyof typeof AgentType];
