// This file was auto-generated by Fern from our API Definition.

/** Status of the AI agent handling the call. */
export const AgentStatus = {
    Pending: "pending",
    Connecting: "connecting",
    Active: "active",
    Completed: "completed",
    Errored: "errored",
    Disconnected: "disconnected",
} as const;
export type AgentStatus = (typeof AgentStatus)[keyof typeof AgentStatus];
