// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Account-level cost breakdown by category
 */
export interface AnalyticsCostBreakdownResponse {
    /** Account identifier */
    accountId: string;
    /** Cost breakdown by service category (LLM, TTS, STT, telephony) */
    byCategory: Talkif.CategoryBreakdown[];
    /** Cost breakdown by flow */
    byFlow: Talkif.FlowCostBreakdown[];
    /**
     * Individual calls with per-category breakdown, for drill-down.
     * Ordered by created_at DESC, limited to the most recent calls in the period.
     */
    calls: Talkif.CallCostDetail[];
    /** End of the reporting period */
    endDate: string;
    /** Time period label */
    period: string;
    /** Start of the reporting period */
    startDate: string;
    /** Total cost in microcents (1 cent = 10,000 microcents) */
    totalMicrocents: number;
    /** Total cost in USD */
    totalUsd: number;
}
