// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Available phone number from Twilio search
 *
 * Based on Twilio AvailablePhoneNumberLocal API response
 * See: https://www.twilio.com/docs/phone-numbers/api/availablephonenumberlocal-resource
 */
export interface AvailablePhoneNumber {
    /** Type of address required to purchase this number (none, any, local, foreign) */
    addressRequirements: string;
    /** Whether the phone number is new to the Twilio platform */
    beta: boolean;
    /** Capabilities of this phone number (Voice, SMS, MMS) */
    capabilities: Talkif.PhoneNumberCapability[];
    /** Formatted version of the phone number */
    friendlyName: string;
    /** ISO country code of this phone number */
    isoCountry: string;
    /** LATA of this phone number (US/Canada only) */
    lata?: (string | null) | undefined;
    /** Latitude of this phone number's location (US/Canada only) */
    latitude?: (number | null) | undefined;
    /** Locality/city of this phone number's location (US/Canada only) */
    locality?: (string | null) | undefined;
    /** Longitude of this phone number's location (US/Canada only) */
    longitude?: (number | null) | undefined;
    /** Phone number in E.164 format */
    phoneNumber: string;
    /** Postal or ZIP code (US/Canada only) */
    postalCode?: (string | null) | undefined;
    /** Rate center of this phone number (US/Canada only) */
    rateCenter?: (string | null) | undefined;
    /** Two-letter state or province abbreviation (US/Canada only) */
    region?: (string | null) | undefined;
}
