// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Balance transaction response
 */
export interface BalanceTransactionResponse {
    /** Transaction amount in USD (negative for debits, positive for credits) */
    amount: string;
    /** Account balance after this transaction (USD) */
    balanceAfter: string;
    /** Account balance before this transaction (USD) */
    balanceBefore: string;
    /** When the transaction occurred */
    createdAt: string;
    /** Human-readable transaction description */
    description?: (string | null) | undefined;
    /** Unique transaction identifier */
    id: string;
    /** ID of the related entity (e.g., call ID, charge ID) */
    referenceId?: (string | null) | undefined;
    /** Type of the related entity (e.g., "call", "phone") */
    referenceType?: (string | null) | undefined;
    /** Current transaction status */
    status: Talkif.TransactionStatus;
    /** Type of transaction */
    transactionType: Talkif.TransactionType;
}
