// This file was auto-generated by Fern from our API Definition.

/**
 * Result of a bulk remove-by-filter operation
 */
export interface BulkRemoveContactsResponse {
    /** Number of campaign contacts matching the filter */
    matched: number;
    /** Number actually removed */
    removed: number;
    /** Number left in place because they were already called or in the queue */
    skipped: number;
}
