// This file was auto-generated by Fern from our API Definition.

/**
 * Bulk import response
 */
export interface BulkDncImportResponse {
    /** Number of new DNC entries added */
    added: number;
    /** Number of entries skipped because they were already on the DNC list */
    skipped: number;
}
