// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Filter criteria for bulk adding contacts to a campaign
 *
 * At least one filter must be provided. Filters are combined with AND logic:
 * - If both `tags` and `company` are specified, contacts must match BOTH
 * - Use `tagMode` to control tag matching: "any" (OR) or "all" (AND)
 */
export interface BulkContactFilter {
    /** Filter by company name (exact match, case-sensitive) */
    company?: (string | null) | undefined;
    /** Full-text search across name, company, occupation, and email */
    search?: (string | null) | undefined;
    /** How to match multiple tags: `any` (OR, default) or `all` (AND) */
    tagMode?: Talkif.BulkTagFilterMode | undefined;
    /** Tags to filter by, matching behavior controlled by `tagMode` */
    tags?: (string[] | null) | undefined;
}
