// This file was auto-generated by Fern from our API Definition.

/**
 * Response for bulk add operation
 */
export interface BulkAddContactsResponse {
    /** Number of contacts successfully added to the campaign */
    added: number;
    /** Total number of contacts that matched the filter criteria */
    matched: number;
    /** Number of contacts skipped because they were already in the campaign */
    skipped: number;
}
