// This file was auto-generated by Fern from our API Definition.

/** Tag filter mode for bulk operations */
export const BulkTagFilterMode = {
    Any: "any",
    All: "all",
} as const;
export type BulkTagFilterMode = (typeof BulkTagFilterMode)[keyof typeof BulkTagFilterMode];
