// This file was auto-generated by Fern from our API Definition.

/**
 * Call rate metrics
 */
export interface CallRates {
    /** Percentage of calls that failed (0-100) */
    failureRate: number;
    /** Percentage of calls that completed successfully (0-100) */
    successRate: number;
}
