// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Call response (for history, details)
 *
 * Represents both initiated calls and queued calls.
 * If `queue_info` is present, the call is pending in the queue.
 *
 * This struct is used for:
 * - API responses (GET /calls, GET /calls/:id)
 * - SSE `call-created` event payload
 * - Subscribe response `activeCalls` array
 */
export interface CallResponse {
    /** Account that owns this call */
    accountId: string;
    /** When the AI agent connected to the call */
    agentConnectedAt?: (string | null) | undefined;
    /** When the AI agent disconnected from the call */
    agentDisconnectedAt?: (string | null) | undefined;
    /** Status of the AI agent handling the call. */
    agentStatus: Talkif.AgentStatus;
    /** Bot speech duration in seconds */
    botSpeechSecs?: (number | null) | undefined;
    /** Twilio Call SID, empty string for calls not yet assigned a SID */
    callSid?: string | undefined;
    /** Campaign ID if the call is part of a bulk campaign */
    campaignId?: (string | null) | undefined;
    /** LLM completion (output) tokens generated */
    completionTokens?: (number | null) | undefined;
    contact?: (Talkif.ContactBrief | null) | undefined;
    /** Total call cost in USD (string for decimal precision) */
    cost?: (string | null) | undefined;
    /** When the call record was created */
    createdAt: string;
    /** When PII fields were scrubbed by the data retention job (null if not scrubbed) */
    dataRetainedAt?: (string | null) | undefined;
    /** Call direction (inbound or outbound) */
    direction: Talkif.CallDirection;
    /** Call duration in seconds */
    duration?: (number | null) | undefined;
    endReason?: (Talkif.CallEndReason | null) | undefined;
    /** When the call ended */
    endedAt?: (string | null) | undefined;
    failureCode?: (Talkif.CallFailureCode | null) | undefined;
    /** Human-readable failure description */
    failureReason?: (string | null) | undefined;
    /** Client connect to first bot audio in milliseconds */
    firstSpeechMs?: (number | null) | undefined;
    /** Flow ID used for the AI conversation */
    flowId?: (string | null) | undefined;
    /** Caller phone number in E.164 format */
    fromNumber: string;
    /** Total function calls made during the call */
    functionCallCount?: (number | null) | undefined;
    /** Total time spent in function calls in milliseconds */
    functionCallTotalMs?: (number | null) | undefined;
    /** Unique call identifier */
    id: string;
    /** Turns where user interrupted the bot */
    interruptedTurns?: (number | null) | undefined;
    /** Whether AI-powered post-call analysis has been performed */
    isAnalyzed: boolean;
    /** True if a Meta lead-form submission triggered this call */
    isLead?: boolean | undefined;
    /** Whether audio recording was enabled for this call */
    isRecorded: boolean;
    /** LLM prompt (input) tokens consumed */
    promptTokens?: (number | null) | undefined;
    providerType?: (Talkif.CallProviderType | null) | undefined;
    queueInfo?: (Talkif.QueueInfo | null) | undefined;
    /** Recording duration in seconds */
    recordingDurationSecs?: (number | null) | undefined;
    /** When the recording will be automatically deleted from storage */
    recordingExpiresAt?: (string | null) | undefined;
    /** Recording file size in bytes */
    recordingFileSizeBytes?: (number | null) | undefined;
    /** Recording lifecycle status */
    recordingStatus?: (string | null) | undefined;
    /** Upfront recording storage cost in USD */
    recordingStorageCost?: (string | null) | undefined;
    /** Schedule ID if the call was triggered by a recurring schedule */
    scheduleId?: (string | null) | undefined;
    /** Where the call originated from */
    source: Talkif.CallSource;
    /** When the call was answered */
    startedAt?: (string | null) | undefined;
    /** User-facing computed status derived from telephony and agent layers */
    status: Talkif.CallStatus;
    /** Telephony layer status (PSTN/Twilio) */
    telephonyStatus: Talkif.TelephonyStatus;
    /** Destination phone number in E.164 format */
    toNumber: string;
    /** What triggered the call — lead form, campaign, or schedule name (for display next to source) */
    triggerDetail?: (string | null) | undefined;
    /** TTS characters synthesized */
    ttsCharacters?: (number | null) | undefined;
    /** Total conversation turns */
    turnCount?: (number | null) | undefined;
    /** User speech duration in seconds */
    userSpeechSecs?: (number | null) | undefined;
    /** When voicemail detection produced a result (null if none) */
    voicemailDetectedAt?: (string | null) | undefined;
    /**
     * Voicemail detection outcome (null if detection was off or no result):
     * "voicemail_detected", "human_detected", or "undetermined"
     */
    voicemailStatus?: (string | null) | undefined;
}
