// This file was auto-generated by Fern from our API Definition.

/**
 * Tracks the specific reason a call failed, enabling:
 * - Analytics (which failure types are most common)
 * - Callbacks (schedule callback for capacity-rejected inbound calls)
 * - Debugging (detailed failure tracking)
 */
export const CallFailureCode = {
    CapacityLimit: "capacity_limit",
    RateLimit: "rate_limit",
    InsufficientBalance: "insufficient_balance",
    PhoneNotActive: "phone_not_active",
    FlowNotPublished: "flow_not_published",
    ProviderError: "provider_error",
    NetworkError: "network_error",
    InvalidNumber: "invalid_number",
    Busy: "busy",
    NoAnswer: "no_answer",
    Rejected: "rejected",
    Canceled: "canceled",
    Timeout: "timeout",
    Unknown: "unknown",
    AgentTimeout: "agent_timeout",
    AgentError: "agent_error",
    AgentDisconnected: "agent_disconnected",
    UnknownPhoneNumber: "unknown_phone_number",
    NoConnectedFlow: "no_connected_flow",
    BotUnavailable: "bot_unavailable",
    FlowNotFound: "flow_not_found",
    SystemError: "system_error",
    ServiceError: "service_error",
    ConfigInvalid: "config_invalid",
    RoutingError: "routing_error",
} as const;
export type CallFailureCode = (typeof CallFailureCode)[keyof typeof CallFailureCode];
