// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination metadata for list responses
 */
export interface CallListMeta {
    /** Maximum number of items per page */
    limit: number;
    /** Number of items skipped (offset into the result set) */
    offset: number;
    /** Total number of matching records across all pages */
    total: number;
}
