// This file was auto-generated by Fern from our API Definition.

/**
 * Call count breakdown
 */
export interface CallCounts {
    /** Calls that completed successfully */
    completed: number;
    /** Calls that failed due to errors */
    failed: number;
    /** Calls currently in progress */
    inProgress: number;
    /** Calls where the recipient did not answer */
    noAnswer: number;
    /** Total number of calls in the period */
    total: number;
}
