// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Call cost detail with per-category breakdown for drill-down
 */
export interface CallCostDetail {
    /** Cost breakdown by category for this call */
    byCategory: Talkif.CategoryBreakdown[];
    /** Call identifier */
    callId: string;
    /** Contact identifier */
    contactId?: (string | null) | undefined;
    /** When the call was created */
    createdAt: string;
    /** Call direction (inbound or outbound) */
    direction?: (string | null) | undefined;
    /** Call duration in seconds */
    durationSeconds?: (number | null) | undefined;
    /** Associated flow identifier */
    flowId?: (string | null) | undefined;
    /** Flow display name */
    flowName?: (string | null) | undefined;
    /** Call cost in microcents */
    totalMicrocents: number;
    /** Call cost in USD */
    totalUsd: number;
}
