// This file was auto-generated by Fern from our API Definition.

/** Provider type */
export const CallProviderType = {
    Twilio: "twilio",
    Sip: "sip",
    Webrtc: "webrtc",
    Whatsapp: "whatsapp",
} as const;
export type CallProviderType = (typeof CallProviderType)[keyof typeof CallProviderType];
