// This file was auto-generated by Fern from our API Definition.

/**
 * Call status state machine
 *
 * State transitions:
 * ```text
 * QUEUED → INITIATED → RINGING → IN_PROGRESS → COMPLETED/FAILED/BUSY/NO_ANSWER/CANCELED
 * ```
 */
export const CallStatus = {
    Queued: "queued",
    Initiated: "initiated",
    Ringing: "ringing",
    Inprogress: "inprogress",
    Completed: "completed",
    Failed: "failed",
    Busy: "busy",
    Noanswer: "noanswer",
    Canceled: "canceled",
} as const;
export type CallStatus = (typeof CallStatus)[keyof typeof CallStatus];
