// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Call transcript response containing the full conversation text
 */
export interface CallTranscriptResponse {
    /** Call identifier */
    callId: string;
    /** Call duration in seconds */
    duration?: (number | null) | undefined;
    /** When the call ended */
    endedAt?: (string | null) | undefined;
    /** Structured transcript, in the order the turns were spoken */
    messages: Talkif.TranscriptMessage[];
    /** When the call started */
    startedAt: string;
    /** Full transcript text of the conversation, one line per turn */
    transcript: string;
}
