// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Paginated list of campaigns
 */
export interface CampaignListResponse {
    /** List of campaigns for the current page */
    campaigns: Talkif.CampaignResponse[];
    /** Pagination metadata */
    meta: Talkif.ListMeta;
}
