// This file was auto-generated by Fern from our API Definition.

/**
 * One bucket of the call-duration histogram.
 */
export interface CampaignDurationBucket {
    bucket: string;
    count: number;
    percentage: number;
}
