// This file was auto-generated by Fern from our API Definition.

/**
 * Campaign overview totals
 */
export interface CampaignOverview {
    /** Average call duration in seconds */
    avgDurationSeconds: number;
    /** Calls that completed successfully */
    completed: number;
    /** Calls that failed */
    failed: number;
    /** Calls with no answer */
    noAnswer: number;
    /** Contacts skipped (DNC, opt-out) */
    skipped: number;
    /** Success rate percentage (0-100) */
    successRate: number;
    /** Total calls made in the campaign */
    totalCalls: number;
    /** Total cost in USD */
    totalCost: string;
    /** Total call duration in seconds */
    totalDurationSeconds: number;
}
