// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Campaign contact response
 */
export interface CampaignContactResponse {
    /** Number of call attempts made so far */
    attemptCount: number;
    /** ID of the latest call for this contact */
    callId?: (string | null) | undefined;
    /** When the latest call completed */
    completedAt?: (string | null) | undefined;
    /** Snapshotted contact email from when the contact was added */
    contactEmail?: (string | null) | undefined;
    /** Underlying contact ID from the contacts table */
    contactId: string;
    /** Snapshotted contact name from when the contact was added */
    contactName?: (string | null) | undefined;
    /** Failure reason from the latest call, or skip reason if skipped */
    failureReason?: (string | null) | undefined;
    /** Unique identifier for this campaign contact entry */
    id: string;
    /** Maximum allowed call attempts */
    maxAttempts: number;
    /** Contact's phone number in E.164 format */
    phoneNumber: string;
    /** Queue priority (lower value = higher priority) */
    priority: number;
    /** When the contact was skipped (if status is `skipped`) */
    skippedAt?: (string | null) | undefined;
    /** Derived status based on the latest call record */
    status: Talkif.CampaignContactStatus;
    /** Contact's IANA timezone (used when `respectContactTimezone` is enabled) */
    timezone?: (string | null) | undefined;
}
