// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Paginated list of campaign contacts
 */
export interface CampaignContactListResponse {
    /** List of campaign contacts for the current page */
    contacts: Talkif.CampaignContactResponse[];
    /** Pagination metadata */
    meta: Talkif.ListMeta;
}
