// This file was auto-generated by Fern from our API Definition.

/**
 * Campaign contact status
 *
 * Status is derived from the calls table (single source of truth):
 * - If `skipped_at` is set → Skipped (highest priority, DNC/opt-out)
 * - If contact has call record → Derive from call.status
 * - If no call record → Pending (waiting to be called)
 *
 * Note: Campaign-level `not_called` count tracks contacts never called when campaign ends
 */
export const CampaignContactStatus = {
    Pending: "pending",
    Queued: "queued",
    Calling: "calling",
    Completed: "completed",
    Failed: "failed",
    NoAnswer: "no_answer",
    Skipped: "skipped",
} as const;
export type CampaignContactStatus = (typeof CampaignContactStatus)[keyof typeof CampaignContactStatus];
