// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Campaign analytics deep-dive response
 */
export interface CampaignAnalyticsResponse {
    /** Distribution of contacts by attempt count */
    attemptDistribution: Talkif.AttemptBucket[];
    /** Campaign identifier */
    campaignId: string;
    /** Cost breakdown by service category */
    costBreakdown: Talkif.CategoryBreakdown[];
    /** Call-duration histogram; an average hides a bimodal distribution. */
    durationBuckets: Talkif.CampaignDurationBucket[];
    /** Failures grouped by structured cause, most common first. */
    failureCauses: Talkif.CampaignFailureCause[];
    /** Hourly call volume throughout campaign lifetime */
    hourlyVolume: Talkif.HourlyVolume[];
    /** Contact outcome breakdown with percentages */
    outcomes: Talkif.CampaignOutcome[];
    /** Overview metrics */
    overview: Talkif.CampaignOverview;
    /** Performance metrics (latency, conversation, usage, function calls) */
    performance: Talkif.CampaignPerformance;
    /** Answering-machine detection outcomes. */
    voicemail: Talkif.CampaignVoicemail;
}
