// This file was auto-generated by Fern from our API Definition.

/**
 * Answering-machine detection outcomes.
 */
export interface CampaignVoicemail {
    human: number;
    undetermined: number;
    voicemail: number;
    /**
     * Voicemail as a share of calls where detection reached a verdict (0-100).
     * Null when nothing was ever classified.
     */
    voicemailRate?: (number | null) | undefined;
}
