// This file was auto-generated by Fern from our API Definition.

/**
 * A failure cause with its share of the campaign's failures.
 */
export interface CampaignFailureCause {
    /** Stable machine code from the `call_failure_code` enum. */
    code: string;
    count: number;
    /** Most recent free-text detail for this code, when one exists. */
    example?: (string | null) | undefined;
    /** Human label derived from the code. */
    label: string;
    /** 0-100 share of failures. */
    percentage: number;
}
