// This file was auto-generated by Fern from our API Definition.

/**
 * Campaign status
 *
 * Full lifecycle with draining support:
 * - Draft: Being configured, contacts can be added
 * - Pending: User clicked start, contacts being queued
 * - Running: Actively processing queued contacts
 * - Draining: Pause requested, waiting for active calls to finish
 * - Paused: Fully stopped, can add contacts or resume
 * - Completed: All contacts processed
 * - Canceled: Manually stopped
 */
export const CampaignStatus = {
    Draft: "draft",
    Pending: "pending",
    Running: "running",
    Draining: "draining",
    Paused: "paused",
    Completed: "completed",
    Canceled: "canceled",
} as const;
export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus];
