// This file was auto-generated by Fern from our API Definition.

/**
 * Single category cost breakdown
 */
export interface CategoryBreakdown {
    /** Category identifier (e.g., "llm_conversation", "tts", "stt", "twilio_voice") */
    category: string;
    /** Human-readable category name */
    categoryDisplay: string;
    /** Percentage of total cost (0-100) */
    percentage: number;
    /** Cost in microcents */
    totalMicrocents: number;
    /** Cost in USD */
    totalUsd: number;
}
