// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Top-level change summary stored in flow_versions.change_summary
 */
export interface ChangeSummary {
    /** Agent-level changes (added, removed, modified) */
    agents: Talkif.AgentChangeSummary;
    /** Detailed list of all changes */
    changes: Talkif.FlowChange[];
    /** Flow-level setting changes */
    flow: Talkif.FlowSettingChanges;
    /** Service configuration changes (LLM, TTS, STT) */
    services: Talkif.ServiceChangeSummary;
    /** Total number of individual changes detected */
    totalChanges: number;
}
