// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of charges
 */
export interface ChargeListResponse {
    /** Items on this page */
    charges: Talkif.ChargeResponse[];
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
}
