// This file was auto-generated by Fern from our API Definition.

/**
 * Connected flow information (populated when flow is connected)
 */
export interface ConnectedFlow {
    /** Optional description of the flow */
    description?: (string | null) | undefined;
    /** Unique identifier of the connected flow */
    id: string;
    /** Display name of the flow */
    name: string;
    /** Timestamp when the flow was last published */
    publishedAt?: (string | null) | undefined;
}
