// This file was auto-generated by Fern from our API Definition.

/**
 * Minimal phone number info for flow listing
 */
export interface ConnectedPhoneSummary {
    /** Human-readable label for the phone number */
    friendlyName?: (string | null) | undefined;
    /** Unique identifier of the phone number resource */
    id: string;
    /** Phone number in E.164 format */
    phoneNumber: string;
}
