// This file was auto-generated by Fern from our API Definition.

/**
 * Contact entity
 */
export interface Contact {
    /** Account that owns this contact */
    accountId: string;
    /** Structured address (street, city, state, zip, country) */
    address: Record<string, unknown>;
    /** Company or organization name */
    company?: (string | null) | undefined;
    /** Timestamp when the contact was created */
    createdAt: string;
    /** Timestamp when the contact was soft-deleted, if applicable */
    deletedAt?: (string | null) | undefined;
    /** Email address */
    email?: (string | null) | undefined;
    /** Unique identifier for the contact */
    id: string;
    /** Contact interests or topics */
    interests: string[];
    /** BCP 47 language code */
    language: string;
    /** Timestamp of the most recent call with this contact */
    lastContactedAt?: (string | null) | undefined;
    /** Full name of the contact */
    name: string;
    /** Free-text notes about the contact */
    notes?: (string | null) | undefined;
    /** Job title or occupation */
    occupation?: (string | null) | undefined;
    /** Primary phone number in E.164 format */
    primaryPhone: string;
    /** Additional phone numbers in E.164 format */
    secondaryPhones: string[];
    /** Tags for categorization and filtering */
    tags: string[];
    /** IANA timezone identifier */
    timezone?: (string | null) | undefined;
    /** Timestamp when the contact was last updated */
    updatedAt: string;
}
