// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Contact list response
 */
export interface ContactListResponse {
    /** List of contacts matching the query */
    contacts: Talkif.Contact[];
    /** Pagination metadata */
    meta: Talkif.ContactPaginationMeta;
}
