// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination metadata
 */
export interface ContactPaginationMeta {
    /** Maximum items returned per page */
    limit: number;
    /** Number of items skipped */
    offset: number;
    /** Total number of matching records */
    total: number;
}
