// This file was auto-generated by Fern from our API Definition.

/**
 * Cost metrics
 */
export interface CostMetrics {
    /** Average cost per call formatted as USD string */
    average: string;
    /** Total cost formatted as USD string */
    total: string;
}
