// This file was auto-generated by Fern from our API Definition.

/** Cost category for line items */
export const CostCategory = {
    LlmConversation: "llm_conversation",
    Stt: "stt",
    Tts: "tts",
    Telephony: "telephony",
    Infrastructure: "infrastructure",
    FunctionCall: "function_call",
    LlmAnalysis: "llm_analysis",
    LlmClassification: "llm_classification",
    AssistantUsage: "assistant_usage",
    NumberFee: "number_fee",
    RentalFee: "rental_fee",
    RecordingStorage: "recording_storage",
} as const;
export type CostCategory = (typeof CostCategory)[keyof typeof CostCategory];
