// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Create contact request
 */
export interface CreateContactRequest {
    address?: (Talkif.ContactAddress | null) | undefined;
    /** Company or organization name */
    company?: (string | null) | undefined;
    /** Email address */
    email?: (string | null) | undefined;
    /** Contact interests or topics (max 50) */
    interests?: (string[] | null) | undefined;
    /** BCP 47 language code (2-10 characters) */
    language?: (string | null) | undefined;
    /** Full name of the contact (1-255 characters) */
    name: string;
    /** Free-text notes (max 5000 characters) */
    notes?: (string | null) | undefined;
    /** Job title or occupation */
    occupation?: (string | null) | undefined;
    /** Primary phone number in E.164 format */
    primaryPhone: string;
    /** Additional phone numbers in E.164 format (max 10) */
    secondaryPhones?: (string[] | null) | undefined;
    /** Tags for categorization (max 50) */
    tags?: (string[] | null) | undefined;
    /** IANA timezone identifier */
    timezone?: (string | null) | undefined;
}
