// This file was auto-generated by Fern from our API Definition.

/**
 * Token-exchange response.
 */
export interface CreatePublicSessionResponse {
    /** Seconds until the token expires */
    expiresIn: number;
    /** Flow this session may call */
    flowId: string;
    /** Signed session token — send as `Authorization: Bearer <token>` */
    token: string;
}
