// This file was auto-generated by Fern from our API Definition.

/**
 * Intent detected from the conversation by AI analysis
 */
export interface DetectedIntent {
    /** Confidence level: "high", "medium", or "low" */
    confidence?: (string | null) | undefined;
    /** Intent name describing what the caller wanted */
    name: string;
}
