// This file was auto-generated by Fern from our API Definition.

/**
 * DNC entry response
 */
export interface DncEntryResponse {
    /** When the DNC entry was created in the system */
    createdAt: string;
    /** Unique identifier for the DNC entry */
    id: string;
    /** Phone number on the DNC list in E.164 format */
    phoneNumber: string;
    /** Human-readable reason for the DNC entry */
    reason?: (string | null) | undefined;
    /** When the DNC request was made */
    requestedAt: string;
    /** How this entry was added (manual, api, call_opt_out, bulk_import) */
    source: string;
}
