// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * DNC list response with pagination
 */
export interface DncListResponse {
    /** DNC entries matching the query */
    entries: Talkif.DncEntryResponse[];
    /** Pagination metadata */
    meta: Talkif.DncListMeta;
}
