// This file was auto-generated by Fern from our API Definition.

/** Duplicate handling strategy when a contact with the same phone number already exists */
export const DuplicateStrategy = {
    Skip: "skip",
} as const;
export type DuplicateStrategy = (typeof DuplicateStrategy)[keyof typeof DuplicateStrategy];
