// This file was auto-generated by Fern from our API Definition.

/**
 * Duration metrics
 */
export interface DurationMetrics {
    /** Average call duration in seconds */
    averageSeconds: number;
    /** Total call duration in seconds across all calls */
    totalSeconds: number;
}
