// This file was auto-generated by Fern from our API Definition.

/**
 * Selectable emotion for a TTS voice.
 */
export interface EmotionOption {
    /** Human-readable display name */
    label: string;
    /** Emotion value to send to API */
    value: string;
}
