// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Standardized error response returned by all API endpoints
 *
 * Every error from the API follows this consistent format:
 *
 * ```json
 * {
 *   "code": "email_already_exists",
 *   "title": "Email Already Exists",
 *   "status": 409,
 *   "detail": "An account with this email already exists",
 *   "requestId": "550e8400-e29b-41d4-a716-446655440000"
 * }
 * ```
 *
 * Validation errors include per-field details in the `errors` array:
 *
 * ```json
 * {
 *   "code": "validation_failed",
 *   "title": "Validation Failed",
 *   "status": 400,
 *   "detail": "Request validation failed",
 *   "requestId": "550e8400-e29b-41d4-a716-446655440000",
 *   "errors": [
 *     { "field": "email", "code": "invalid_format", "message": "Email format is invalid" }
 *   ]
 * }
 * ```
 *
 * Rate limit errors include retry information in the `meta` object:
 *
 * ```json
 * {
 *   "code": "rate_limit_exceeded",
 *   "title": "Rate Limit Exceeded",
 *   "status": 429,
 *   "detail": "Too many requests",
 *   "requestId": "550e8400-e29b-41d4-a716-446655440000",
 *   "meta": { "retryAfterSecs": 60 }
 * }
 * ```
 */
export interface ErrorResponse {
    /** Machine-readable error code for programmatic handling */
    code: Talkif.ErrorCode;
    /** Human-readable detail message for this specific error instance */
    detail: string;
    /** Field-level validation errors, present when code is `validation_failed` */
    errors?: (Talkif.FieldError[] | null) | undefined;
    /** Additional context metadata (e.g., retryAfterSecs for rate limits) */
    meta?: (Record<string, unknown> | null) | undefined;
    /** Unique request identifier for debugging (also in X-Request-Id response header) */
    requestId?: (string | null) | undefined;
    /** HTTP status code (mirrors the response status line) */
    status: number;
    /** Human-readable title for the error category */
    title: string;
}
