// This file was auto-generated by Fern from our API Definition.

/**
 * Single error code entry in the catalog
 */
export interface ErrorCodeEntry {
    /** Error category key for grouping */
    category: string;
    /** Display name for the category (e.g., "API Keys" not "api_keys") */
    categoryTitle: string;
    /** Error code in snake_case format */
    code: string;
    /** Detailed description of when and why this error occurs */
    description: string;
    /** HTTP status code returned with this error */
    status: number;
    /** Human-readable title */
    title: string;
}
