// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Complete error catalog with all error codes and field validation codes
 */
export interface ErrorCatalogResponse {
    /** All API-level error codes grouped by category */
    errorCodes: Talkif.ErrorCodeEntry[];
    /** All field-level validation error codes */
    fieldErrorCodes: Talkif.FieldErrorCodeEntry[];
}
