// This file was auto-generated by Fern from our API Definition.

/**
 * Individual field error for validation responses
 *
 * Appears in the `errors[]` array when `code` is `validation_failed`
 *
 * # Example
 *
 * ```json
 * {
 *   "field": "email",
 *   "code": "invalid_format",
 *   "message": "Email format is invalid"
 * }
 * ```
 */
export interface FieldError {
    /** Specific error code for this field */
    code: string;
    /** The field name that failed validation */
    field: string;
    /** Human-readable error message */
    message: string;
}
