// This file was auto-generated by Fern from our API Definition.

/**
 * Single field-level validation error code entry
 */
export interface FieldErrorCodeEntry {
    /** Field error code in snake_case format */
    code: string;
    /** Detailed description of this validation error */
    description: string;
}
