// This file was auto-generated by Fern from our API Definition.

/** Type of change detected */
export const FlowChangeType = {
    AgentAdded: "agent_added",
    AgentRemoved: "agent_removed",
    AgentModified: "agent_modified",
    ServiceChanged: "service_changed",
    FlowSettingChanged: "flow_setting_changed",
} as const;
export type FlowChangeType = (typeof FlowChangeType)[keyof typeof FlowChangeType];
