// This file was auto-generated by Fern from our API Definition.

/**
 * Flow template - can be system-wide (account_id = None) or account-specific
 */
export interface FlowTemplate {
    /** Account that owns this template (null for system templates) */
    accountId?: (string | null) | undefined;
    /** Template category for filtering */
    category: string;
    /** When the template was created */
    createdAt: string;
    /** User who created this template */
    createdBy?: (string | null) | undefined;
    /**
     * Runtime FlowDefinition (initialNode + services + nodes). This is what
     * instantiation copies into the new flow's definition. Null on legacy
     * templates that only carry builder nodes/edges.
     */
    definition?: (Record<string, unknown> | null) | undefined;
    /** Brief description of what the template does */
    description?: (string | null) | undefined;
    /** Sort order for template listing (lower = first) */
    displayOrder: number;
    /** Flow edge connections between nodes */
    edges: Record<string, unknown>;
    /** Icon identifier or emoji for display */
    icon?: (string | null) | undefined;
    /** Unique template identifier */
    id: string;
    /** ID of the first node to execute */
    initialNode: string;
    /** Whether this template is available for use */
    isActive: boolean;
    /** Template display name */
    name: string;
    /** Flow node definitions */
    nodes: Record<string, unknown>;
    /** URL to a preview image for the template */
    previewImageUrl?: (string | null) | undefined;
    /** URL-safe slug for the template */
    slug: string;
    /** Searchable tags */
    tags?: string[] | undefined;
    /** When the template was last modified */
    updatedAt: string;
}
