// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Flow version detail response (includes full flow data)
 */
export interface FlowVersionDetailResponse {
    /** Bot runtime version used for this published version */
    botVersion?: (string | null) | undefined;
    changeSummary?: (Talkif.ChangeSummary | null) | undefined;
    /** Full transformed definition used by the bot runtime */
    definition?: (Record<string, unknown> | null) | undefined;
    flowDefinition?: (Talkif.FlowDefinition | null) | undefined;
    /** Changelog notes for this version */
    notes?: (string | null) | undefined;
    /** Timestamp when this version was published */
    publishedAt: string;
    /** User ID of the person who published this version */
    publishedBy?: (string | null) | undefined;
    /** Display name of the user who published this version */
    publishedByName?: (string | null) | undefined;
    /** Semantic version string (X.Y.Z) */
    version: string;
}
