// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Flow function response for API
 */
export interface FlowFunctionResponse {
    /** Account that owns this function */
    accountId: string;
    /** Creation timestamp */
    createdAt: string;
    /** Description of what the function does */
    description: string;
    /** Whether encrypted headers are configured (never exposes actual headers) */
    hasWebhookHeaders: boolean;
    /** Unique identifier */
    id: string;
    /** Whether the function is active */
    isActive: boolean;
    /** Display name */
    name: string;
    /**
     * Per-parameter source bindings keyed by flat param name. Empty object `{}`
     * means all params are LLM-extracted. See `CreateFlowFunctionRequest.param_bindings`.
     */
    paramBindings: Record<string, unknown>;
    /** Structured HTTP request shape (method, url, pathParams, queryParams, body) */
    request: Talkif.RequestSchema;
    /** URL-safe slug */
    slug: string;
    /** Timeout in milliseconds */
    timeoutMs: number;
    /** Last update timestamp */
    updatedAt: string;
}
