// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of flow functions
 */
export interface FlowFunctionListResponse {
    /** Items on this page */
    functions: Talkif.FlowFunctionResponse[];
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
}
