// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Flow detail response for API (includes full flow data)
 *
 * Returns definition + layout as the canonical format.
 */
export interface FlowDetailResponse {
    /** Account that owns this flow */
    accountId: string;
    /** Custom analysis instructions appended to the base analysis prompt */
    analysisInstructions?: (string | null) | undefined;
    /** Call analysis behavior override: "use_account_default", "enabled", or "disabled" */
    analysisOverride: string;
    /** Phone numbers currently connected to this flow */
    connectedPhones: Talkif.ConnectedPhoneSummary[];
    /** Timestamp when the flow was created */
    createdAt: string;
    definition?: (Talkif.FlowDefinition | null) | undefined;
    /** Description of the flow's purpose */
    description?: (string | null) | undefined;
    /** Unique identifier of the flow */
    id: string;
    /** Visual builder layout, if the flow was edited in the builder. */
    layout?: (Record<string, unknown> | null) | undefined;
    maxCallDuration?: (Talkif.MaxCallDurationSettings | null) | undefined;
    /** Display name of the flow */
    name: string;
    /** Timestamp when the flow was last published */
    publishedAt?: (string | null) | undefined;
    /** Recording behavior override: "use_account_default", "enabled", or "disabled" */
    recordingOverride: string;
    /** Current lifecycle status of the flow */
    status: Talkif.FlowStatus;
    /** User-defined tags for filtering and organization */
    tags: string[];
    /** Timestamp when the flow was last updated */
    updatedAt: string;
    userIdle?: (Talkif.UserIdleSettings | null) | undefined;
    /** Current semantic version (X.Y.Z) */
    version: string;
    /** Available published versions (newest first) */
    versions: Talkif.FlowVersionSummary[];
    /** Whether voicemail detection is enabled (outbound Twilio calls only) */
    voicemailEnabled: boolean;
    /** Static voicemail message spoken verbatim (skips the composer LLM call) */
    voicemailMessage?: (string | null) | undefined;
    /** Instruction for composing the voicemail message (ignored if message is set) */
    voicemailMessagePrompt?: (string | null) | undefined;
    /** Seconds to wait after the callee stops speaking before leaving the message */
    voicemailResponseDelaySecs?: (number | null) | undefined;
}
