// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * The canonical flow definition — single source of truth for flow logic, shared by the API and the visual builder.
 *
 * Visual nodes (LLM, TTS, STT, prompt, end_call) collapse into properties:
 * - Service nodes -> `services.*`
 * - Prompt nodes -> `agent.prompt`
 * - Action nodes -> `agent.functions[]`
 * - Edges are implicit — relationships are expressed as data, not connections
 */
export interface FlowDefinition {
    /** Node ID where execution begins (must reference a main_agent node) */
    initialNode: string;
    /** Agent nodes keyed by node ID (e.g., "main_agent_1", "billing_agent") */
    nodes: Record<string, Talkif.AgentDefinition>;
    /** Service provider configuration (LLM, TTS, STT) */
    services: Talkif.ServiceDefinition;
}
