// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Flow response for API (list endpoint - lightweight)
 *
 * Excludes heavy data like definitions.
 * Use FlowDetailResponse for full flow data.
 */
export interface FlowResponse {
    /** Account that owns this flow */
    accountId: string;
    /** Call analysis behavior override: "use_account_default", "enabled", or "disabled" */
    analysisOverride: string;
    /** Phone numbers currently connected to this flow */
    connectedPhones: Talkif.ConnectedPhoneSummary[];
    /** Timestamp when the flow was created */
    createdAt: string;
    /** Description of the flow's purpose */
    description?: (string | null) | undefined;
    /** Unique identifier of the flow */
    id: string;
    /** Display name of the flow */
    name: string;
    /** Total number of nodes in the flow graph */
    nodeCount: number;
    /** Timestamp when the flow was last published */
    publishedAt?: (string | null) | undefined;
    /** Recording behavior override: "use_account_default", "enabled", or "disabled" */
    recordingOverride: string;
    /** Current lifecycle status of the flow */
    status: Talkif.FlowStatus;
    /** User-defined tags for filtering and organization */
    tags: string[];
    /** Timestamp when the flow was last updated */
    updatedAt: string;
    /** Current semantic version (X.Y.Z) */
    version: string;
    /** Available published versions (newest first) */
    versions: Talkif.FlowVersionSummary[];
    /** Whether voicemail detection is enabled (outbound Twilio calls only) */
    voicemailEnabled: boolean;
}
