// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of flow templates
 */
export interface FlowTemplateListResponse {
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
    /** Items on this page */
    templates: Talkif.FlowTemplate[];
}
