// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of flows
 */
export interface FlowListResponse {
    /** Items on this page */
    flows: Talkif.FlowResponse[];
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
}
