// This file was auto-generated by Fern from our API Definition.

/**
 * Lightweight version summary for flow list responses
 *
 * Provides just enough data for version picker dropdowns
 * without the full definition.
 */
export interface FlowVersionSummary {
    /** Changelog notes for this version */
    notes?: (string | null) | undefined;
    /** Timestamp when this version was published */
    publishedAt: string;
    /** Semantic version string (X.Y.Z) */
    version: string;
}
