// This file was auto-generated by Fern from our API Definition.

/**
 * Flow-level cost aggregation
 */
export interface FlowCostBreakdown {
    /** Unique identifier of the flow */
    flowId: string;
    /** Flow display name */
    flowName?: (string | null) | undefined;
    /** Total cost in microcents */
    totalMicrocents: number;
    /** Total cost in USD */
    totalUsd: number;
}
