// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Generation config schema for Cartesia Sonic v3
 */
export interface GenerationConfigSchema {
    /** Speed range configuration */
    speed: Talkif.RangeSchema;
    /** Volume range configuration */
    volume: Talkif.RangeSchema;
}
