// This file was auto-generated by Fern from our API Definition.

/** Import format */
export const ImportFormat = {
    Vcf: "vcf",
    Csv: "csv",
    Json: "json",
} as const;
export type ImportFormat = (typeof ImportFormat)[keyof typeof ImportFormat];
