// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Import error for a single row
 */
export interface ImportError {
    /** Contact name if parseable from the row */
    contactName?: (string | null) | undefined;
    /** Human-readable error description */
    message: string;
    /** Phone number if parseable from the row */
    phone?: (string | null) | undefined;
    /** Machine-readable error category */
    reason: Talkif.ErrorReason;
    /** Row number in the source file (1-indexed) */
    row: number;
}
