// This file was auto-generated by Fern from our API Definition.

/** Invoice status (matches Stripe) */
export const InvoiceStatus = {
    Draft: "draft",
    Open: "open",
    Paid: "paid",
    Void: "void",
    Uncollectible: "uncollectible",
} as const;
export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];
