// This file was auto-generated by Fern from our API Definition.

/**
 * Language information for API responses
 */
export interface LanguageInfo {
    /** Language code (e.g., "en", "es") */
    code: string;
    /** Display name in English (e.g., "English", "Spanish") */
    name: string;
    /** Native name (e.g., "English", "Espanol") */
    nativeName: string;
}
