// This file was auto-generated by Fern from our API Definition.

/**
 * Latency performance metrics
 */
export interface LatencyMetrics {
    /** Average first speech latency in milliseconds (client connect to first bot audio) */
    avgFirstSpeechMs?: (number | null) | undefined;
    /** Median first speech latency in milliseconds */
    p50FirstSpeechMs?: (number | null) | undefined;
    /** 95th percentile first speech latency */
    p95FirstSpeechMs?: (number | null) | undefined;
}
