// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * LLM provider with models and pricing
 */
export interface LlmProvider {
    /** Display name (e.g., "OpenAI", "Anthropic") */
    displayName: string;
    /** Available models with pricing */
    models: Talkif.LlmModel[];
    /** Provider identifier (e.g., "openai", "anthropic") */
    provider: string;
}
