// This file was auto-generated by Fern from our API Definition.

/**
 * LLM pricing from database
 */
export interface LlmPricing {
    /** Human-readable input rate (e.g., "$2.50") */
    inputPer1mTokensDisplay: string;
    /** Rate per 1M input tokens in microcents */
    inputPer1mTokensMicrocents: number;
    /** Human-readable output rate (e.g., "$10.00") */
    outputPer1mTokensDisplay: string;
    /** Rate per 1M output tokens in microcents */
    outputPer1mTokensMicrocents: number;
}
