// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Paginated list response wrapper
 *
 * Generic wrapper for list responses that includes items and pagination metadata
 */
export interface PaginatedResponse {
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
}
