// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination metadata in responses
 */
export interface PaginationMeta {
    /** Number of items in current response */
    limit: number;
    /** Number of items skipped */
    offset: number;
    /** Total number of items available */
    total: number;
}
