// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of phone providers
 */
export interface PhoneProviderListResponse {
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
    /** Items on this page */
    providers: Talkif.PhoneProviderResponse[];
}
