// This file was auto-generated by Fern from our API Definition.

/** Phone number status */
export const PhoneNumberStatus = {
    Active: "ACTIVE",
    Pending: "PENDING",
    Suspended: "SUSPENDED",
    Released: "RELEASED",
} as const;
export type PhoneNumberStatus = (typeof PhoneNumberStatus)[keyof typeof PhoneNumberStatus];
