// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Phone number response for API
 *
 * Note: `voice_url` and `sms_url` are internal system URLs and not exposed to users
 * They are auto-generated when connecting flows and point to internal webhook endpoints
 */
export interface PhoneNumberResponse {
    /** Account that owns this phone number */
    accountId: string;
    /** Current billing status (active, processing, past_due, suspended) */
    billingStatus: string;
    /** Whether this number can place outbound calls (WhatsApp numbers are receive-only) */
    canInitiateCalls: boolean;
    /** Supported capabilities (voice, SMS, MMS) */
    capabilities: Talkif.PhoneNumberCapability[];
    /** Routing channel of this number (pstn or whatsapp) */
    channelType: Talkif.ChannelType;
    /** Timestamp when a flow was connected to this number */
    connectedAt?: (string | null) | undefined;
    connectedFlow?: (Talkif.ConnectedFlow | null) | undefined;
    /** Timestamp when the record was created */
    createdAt: string;
    /** User-assigned friendly name for the number */
    friendlyName?: (string | null) | undefined;
    /** Unique identifier of the phone number */
    id: string;
    /** Whether the phone number has been verified via caller ID validation */
    isVerified: boolean;
    /** Monthly recurring cost formatted as a decimal string */
    monthlyCost: string;
    /** Next scheduled billing date for the monthly charge */
    nextBillingDate?: (string | null) | undefined;
    /** Phone number in E.164 format */
    phoneNumber: string;
    /** Provider through which this number was provisioned */
    providerId: string;
    /** Provider-specific phone number identifier (e.g. Twilio SID) */
    providerPhoneId: string;
    /** Timestamp when the number was purchased */
    purchasedAt: string;
    /** Recording override setting for calls on this number */
    recordingOverride: string;
    /** Timestamp when the number was released, if applicable */
    releasedAt?: (string | null) | undefined;
    /** Current status of the phone number */
    status: Talkif.PhoneNumberStatus;
    /** Twilio edge location for SIP signaling (e.g. ashburn, frankfurt) */
    twilioEdge: string;
    /** Twilio API region (us1 or ie1) */
    twilioRegion: string;
    /** Timestamp when the record was last updated */
    updatedAt: string;
    /** Timestamp when the number was verified */
    verifiedAt?: (string | null) | undefined;
}
