// This file was auto-generated by Fern from our API Definition.

/**
 * Phone number pricing information
 */
export interface PhoneNumberPricing {
    /** ISO country code */
    countryCode: string;
    /** Full country name */
    countryName: string;
    /** Monthly recurring price as a decimal string */
    pricePerMonth: string;
    /** Currency code for the price */
    priceUnit: string;
}
