// This file was auto-generated by Fern from our API Definition.

/**
 * Deprecated prompt wrapper, accepted for backwards compatibility. New definitions put the prompt inline in `AgentDefinition.agentPrompt`.
 */
export interface PromptReference {
    /** Inline content override (may contain {{handlebars}} expressions) */
    content?: (string | null) | undefined;
    /**
     * Prompt template UUID (references prompt_templates table).
     * Optional — omit for inline-only prompts that don't reference a saved template.
     */
    templateId?: (string | null) | undefined;
}
