// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Public pricing response for telephony, phone numbers, and storage
 *
 * LLM/STT/TTS pricing is served by `/api/v1/models/*` with richer data
 * (capabilities, languages, use-case filtering).
 */
export interface PublicPricingResponse {
    /** Phone number purchase and rental pricing */
    phoneNumbers: Talkif.PublicPhoneNumberPricing;
    /** Recording storage pricing */
    recordingStorage: Talkif.RecordingStoragePricing;
    /** Telephony provider rates (per-minute pricing) */
    telephony: Talkif.PricingEntry[];
}
