// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Publishing success response (200 OK)
 *
 * Validation failures return ApiError with 400/422 status.
 */
export interface PublishFlowResponse {
    changeSummary?: (Talkif.ChangeSummary | null) | undefined;
    /** Flow detail after publishing */
    flow: Talkif.FlowDetailResponse;
    transformationSummary?: (Talkif.TransformationSummary | null) | undefined;
    /** Newly published version string */
    version: string;
    /** Non-fatal validation warnings that did not block publishing */
    warnings?: (Talkif.FieldError[] | null) | undefined;
}
