// This file was auto-generated by Fern from our API Definition.

/**
 * Queue information for a call that's pending in the call queue
 */
export interface QueueInfo {
    /** Number of processing attempts made so far */
    attemptCount: number;
    /** Estimated wait time before the call is processed (seconds) */
    estimatedWaitSeconds?: (number | null) | undefined;
    /** Position in queue (1-indexed, lower is sooner) */
    position: number;
    /** Unique queue entry identifier */
    queueId: string;
    /** When the call was added to the queue */
    queuedAt: string;
    /** Queue processing status: "pending", "reserved", or "processing" */
    status: string;
}
