// This file was auto-generated by Fern from our API Definition.

/**
 * Pre-signed URL response for accessing a call recording
 */
export interface RecordingUrlResponse {
    /** Recording duration in seconds */
    durationSecs?: (number | null) | undefined;
    /** Seconds until the pre-signed URL expires */
    expiresInSecs: number;
    /** Recording file size in bytes */
    fileSizeBytes?: (number | null) | undefined;
    /** When the recording will be permanently deleted from storage (ISO 8601) */
    recordingExpiresAt?: (string | null) | undefined;
    /** Pre-signed S3 URL to download the recording */
    url: string;
}
