// This file was auto-generated by Fern from our API Definition.

/**
 * Response indicating how many contacts were removed
 */
export interface RemovedResponse {
    /** Number of contacts removed from the campaign */
    removed: number;
}
