// This file was auto-generated by Fern from our API Definition.

/** Schedule status */
export const ScheduleStatus = {
    Active: "active",
    Paused: "paused",
    Completed: "completed",
    Canceled: "canceled",
} as const;
export type ScheduleStatus = (typeof ScheduleStatus)[keyof typeof ScheduleStatus];
