// This file was auto-generated by Fern from our API Definition.

/** Schedule frequency type */
export const ScheduleFrequency = {
    Once: "once",
    Daily: "daily",
    Weekly: "weekly",
    Monthly: "monthly",
    CustomCron: "custom_cron",
} as const;
export type ScheduleFrequency = (typeof ScheduleFrequency)[keyof typeof ScheduleFrequency];
