// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Schedule response
 */
export interface ScheduleResponse {
    /** Contact to call on each execution */
    contactId: string;
    /** When the schedule was created */
    createdAt: string;
    /** Custom cron expression (when frequency is `custom_cron`) */
    cronExpression?: (string | null) | undefined;
    /** Day of month (1-28) */
    dayOfMonth?: (number | null) | undefined;
    /** Days of week (1=Monday through 7=Sunday) */
    daysOfWeek?: (number[] | null) | undefined;
    /** Date after which the schedule will not execute */
    endDate?: (string | null) | undefined;
    /** Flow (conversation script) used for the call */
    flowId: string;
    /** Pinned flow version at time of schedule creation */
    flowVersion?: (string | null) | undefined;
    /** How often the schedule repeats */
    frequency: Talkif.ScheduleFrequency;
    /** Caller ID phone number in E.164 format */
    fromPhoneNumber: string;
    /** Unique identifier for the schedule */
    id: string;
    /** Last execution time in UTC */
    lastRunAt?: (string | null) | undefined;
    /** Maximum retry attempts per execution */
    maxRetries: number;
    /** Maximum number of executions before auto-completing */
    maxRuns?: (number | null) | undefined;
    /** Human-readable name for the schedule */
    name: string;
    /** Next scheduled execution time in UTC */
    nextRunAt?: (string | null) | undefined;
    /** VoIP provider used for routing */
    providerId: string;
    /** Minutes between retry attempts */
    retryDelayMinutes: number;
    /** Whether failed calls are retried */
    retryOnFailure: boolean;
    /** Number of times the schedule has executed so far */
    runCount: number;
    /** Time of day in HH:MM format */
    scheduleTime: string;
    /** Current status of the schedule */
    status: Talkif.ScheduleStatus;
    /** IANA timezone used for schedule_time interpretation */
    timezone: string;
}
