// This file was auto-generated by Fern from our API Definition.

/**
 * Summary of service configuration changes
 */
export interface ServiceChangeSummary {
    /** Whether the LLM service configuration changed */
    llmChanged: boolean;
    /** Whether the STT service configuration changed */
    sttChanged: boolean;
    /** Whether the TTS service configuration changed */
    ttsChanged: boolean;
}
