// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * STT provider with models and pricing
 */
export interface SttProvider {
    /** Display name (e.g., "Deepgram") */
    displayName: string;
    /** Available models with pricing */
    models: Talkif.SttModel[];
    /** Provider identifier (e.g., "deepgram") */
    provider: string;
}
