// This file was auto-generated by Fern from our API Definition.

/**
 * STT service configuration
 *
 * Supports: deepgram, soniox, elevenlabs, cartesia.
 * Use `language` for single-language providers, `languages` for Soniox multi-language.
 */
export interface SttServiceDefinition {
    /** Keyword boosting terms */
    keywords?: (string[] | null) | undefined;
    /** Display label for UI */
    label?: (string | null) | undefined;
    /** Single language code (Deepgram, ElevenLabs, Cartesia, AssemblyAI, Whisper) */
    language?: (string | null) | undefined;
    /** Language hints array for Soniox multi-language detection */
    languages?: (string[] | null) | undefined;
    /** Model identifier */
    model: string;
    /** Provider identifier */
    provider: string;
}
