// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Tags list response
 */
export interface TagsListResponse {
    /** All tags with their usage counts */
    tags: Talkif.TagWithCount[];
}
