// This file was auto-generated by Fern from our API Definition.

/** Transaction status */
export const TransactionStatus = {
    Pending: "pending",
    Completed: "completed",
    Failed: "failed",
} as const;
export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus];
