// This file was auto-generated by Fern from our API Definition.

/**
 * Per-message latency and usage metrics. Captures the timing breakdown for
 * debugging and analytics.
 */
export interface TranscriptMessageMetrics {
    /** LLM completion (output) tokens generated for this message */
    llmCompletionTokens?: (number | null) | undefined;
    /** LLM total latency from request to complete response in milliseconds */
    llmLatencyMs?: (number | null) | undefined;
    /** LLM prompt (input) tokens consumed for this message */
    llmPromptTokens?: (number | null) | undefined;
    /**
     * Time the model spent thinking in milliseconds (`llm_ttfat_ms` minus
     * `llm_ttfb_ms`), so the cost of reasoning is readable on its own.
     */
    llmThinkingMs?: (number | null) | undefined;
    /**
     * LLM time to first answer token in milliseconds, excluding any reasoning
     * streamed first. On a thinking model this is the latency the caller
     * perceives, where `llm_ttfb_ms` includes the reasoning stream.
     */
    llmTtfatMs?: (number | null) | undefined;
    /** LLM time to first token in milliseconds */
    llmTtfbMs?: (number | null) | undefined;
    /**
     * Speech-to-text total processing time in milliseconds.
     *
     * Deprecated, read-only. Only present on older calls; new transcripts
     * never carry it. Use `sttTtfbMs` (speech end → final transcript) for
     * STT latency.
     */
    sttProcessingMs?: (number | null) | undefined;
    /** Speech-to-text time to first byte in milliseconds */
    sttTtfbMs?: (number | null) | undefined;
    /** First LLM token to first complete sentence in milliseconds */
    textAggregationMs?: (number | null) | undefined;
    /** Number of TTS characters synthesized for this message */
    ttsCharacters?: (number | null) | undefined;
    /** Text-to-speech total processing time in milliseconds */
    ttsProcessingMs?: (number | null) | undefined;
    /** Text-to-speech time to first byte in milliseconds */
    ttsTtfbMs?: (number | null) | undefined;
}
