// This file was auto-generated by Fern from our API Definition.

/** Type of balance transaction */
export const TransactionType = {
    SubscriptionGrant: "subscription_grant",
    Purchase: "purchase",
    Usage: "usage",
    Refund: "refund",
    Adjustment: "adjustment",
    Expiration: "expiration",
    DisputeHold: "dispute_hold",
    DisputeRelease: "dispute_release",
    DisputeLoss: "dispute_loss",
    RefundDeduction: "refund_deduction",
} as const;
export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType];
