// This file was auto-generated by Fern from our API Definition.

/**
 * Agent transition definition
 *
 * Defines a handoff from one agent to another, triggered by keywords
 * in the conversation. Exposed to the LLM as a tool at runtime.
 */
export interface TransitionDefinition {
    /** Keywords/description that trigger this transition */
    keywords?: string | undefined;
    /** Target agent node ID */
    targetAgentId: string;
}
