// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * TTS provider with models and pricing
 */
export interface TtsProvider {
    /** Display name (e.g., "ElevenLabs") */
    displayName: string;
    /** Available models with pricing */
    models: Talkif.TtsModel[];
    /** Provider identifier (e.g., "elevenlabs") */
    provider: string;
}
