// This file was auto-generated by Fern from our API Definition.

/**
 * TTS pricing from database
 */
export interface TtsPricing {
    /** Human-readable rate (e.g., "$0.10") */
    ratePer1kCharsDisplay: string;
    /** Rate per 1000 characters in microcents (1 cent = 10,000 microcents) */
    ratePer1kCharsMicrocents: number;
}
