// This file was auto-generated by Fern from our API Definition.

/**
 * TTS service configuration
 *
 * Supports: elevenlabs, cartesia.
 * Provider-specific fields are flattened — only relevant fields are set per provider.
 */
export interface TtsServiceDefinition {
    /** Voice emotion preset (Cartesia Sonic v3) */
    emotion?: (string | null) | undefined;
    /** Display label for UI */
    label?: (string | null) | undefined;
    /** Voice language for localization (Cartesia) */
    language?: (string | null) | undefined;
    /** Model identifier */
    model: string;
    /** Provider identifier */
    provider: string;
    /** Voice similarity boost (0.0 - 1.0, ElevenLabs) */
    similarity?: (number | null) | undefined;
    /** Speaker boost (ElevenLabs) */
    speakerBoost?: (boolean | null) | undefined;
    /** Speech speed multiplier (Cartesia Sonic v3) */
    speed?: (number | null) | undefined;
    /** Voice stability (0.0 - 1.0, ElevenLabs) */
    stability?: (number | null) | undefined;
    /** Voice style (0.0 - 1.0, ElevenLabs) */
    style?: (number | null) | undefined;
    /** Voice identifier */
    voiceId: string;
    /** Cached voice display name */
    voiceName?: (string | null) | undefined;
    /** Audio volume level (Cartesia Sonic v3) */
    volume?: (number | null) | undefined;
}
