// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Paginated list of TTS voices.
 */
export interface VoicesDto {
    /** Whether there are more results */
    hasMore: boolean;
    /** Token to fetch the next page */
    nextPageToken?: (string | null) | undefined;
    /** Number of voices in this response (post-filter) */
    totalCount: number;
    /** List of voices */
    voices: Talkif.VoiceDto[];
}
