// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "slug"
 *     }
 */
export interface GetFlowTemplateRequest {
    /** Template slug */
    slug: string;
}
