// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Talkif from "../../../index.js";

export declare namespace CampaignsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage bulk calling campaigns
 */
export class CampaignsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CampaignsClient.Options>;

    constructor(options: CampaignsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {Talkif.ListCampaignsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.listCampaigns()
     */
    public async listCampaigns(
        request: Talkif.ListCampaignsRequest = {},
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.Page<Talkif.CampaignResponse, Talkif.CampaignListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Talkif.ListCampaignsRequest,
            ): Promise<core.WithRawResponse<Talkif.CampaignListResponse>> => {
                const { status, search, limit, offset } = request;
                const _queryParams: Record<string, unknown> = {
                    status: status != null ? status : undefined,
                    search,
                    limit,
                    offset,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TalkifEnvironment.Production,
                        "api/v1/campaigns",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Talkif.CampaignListResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 401:
                            throw new Talkif.UnauthorizedError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Talkif.ForbiddenError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Talkif.TooManyRequestsError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Talkif.InternalServerError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TalkifError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/campaigns");
            },
        );
        let _offset = request?.offset != null ? request?.offset : 0;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Talkif.CampaignResponse, Talkif.CampaignListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                (response?.campaigns ?? []).length > 0 &&
                (request?.limit == null || (response?.campaigns ?? []).length >= request?.limit),
            getItems: (response) => response?.campaigns ?? [],
            loadPage: (response) => {
                _offset += response?.campaigns != null ? response.campaigns.length : 1;
                return list(core.setObjectProperty(request, "offset", _offset));
            },
        });
    }

    /**
     * @param {Talkif.CreateCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.createCampaign({
     *         flowId: "550e8400-e29b-41d4-a716-446655440000",
     *         fromPhoneNumber: "+15551234567",
     *         name: "January Outreach",
     *         providerId: "550e8400-e29b-41d4-a716-446655440000"
     *     })
     */
    public createCampaign(
        request: Talkif.CreateCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.CampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createCampaign(request, requestOptions));
    }

    private async __createCampaign(
        request: Talkif.CreateCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.CampaignResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/campaigns",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.CampaignResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/campaigns");
    }

    /**
     * @param {Talkif.GetCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.getCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public getCampaign(
        request: Talkif.GetCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.CampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCampaign(request, requestOptions));
    }

    private async __getCampaign(
        request: Talkif.GetCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.CampaignResponse>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.CampaignResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/campaigns/{campaignId}",
        );
    }

    /**
     * @param {Talkif.UpdateCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.updateCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public updateCampaign(
        request: Talkif.UpdateCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.CampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateCampaign(request, requestOptions));
    }

    private async __updateCampaign(
        request: Talkif.UpdateCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.CampaignResponse>> {
        const { campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.CampaignResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/campaigns/{campaignId}",
        );
    }

    /**
     * @param {Talkif.DeleteCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.deleteCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public deleteCampaign(
        request: Talkif.DeleteCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteCampaign(request, requestOptions));
    }

    private async __deleteCampaign(
        request: Talkif.DeleteCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/campaigns/{campaignId}",
        );
    }

    /**
     * @param {Talkif.CancelCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.UnprocessableEntityError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.cancelCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public cancelCampaign(
        request: Talkif.CancelCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__cancelCampaign(request, requestOptions));
    }

    private async __cancelCampaign(
        request: Talkif.CancelCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Talkif.UnprocessableEntityError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/cancel",
        );
    }

    /**
     * @param {Talkif.ListCampaignContactsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.listCampaignContacts({
     *         campaignId: "campaignId"
     *     })
     */
    public async listCampaignContacts(
        request: Talkif.ListCampaignContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.Page<Talkif.CampaignContactResponse, Talkif.CampaignContactListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Talkif.ListCampaignContactsRequest,
            ): Promise<core.WithRawResponse<Talkif.CampaignContactListResponse>> => {
                const { campaignId, status, search, limit, offset } = request;
                const _queryParams: Record<string, unknown> = {
                    status: status != null ? status : undefined,
                    search,
                    limit,
                    offset,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TalkifEnvironment.Production,
                        `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/contacts`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Talkif.CampaignContactListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 401:
                            throw new Talkif.UnauthorizedError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Talkif.ForbiddenError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Talkif.NotFoundError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Talkif.TooManyRequestsError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Talkif.InternalServerError(
                                _response.error.body as Talkif.ErrorResponse,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TalkifError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v1/campaigns/{campaignId}/contacts",
                );
            },
        );
        let _offset = request?.offset != null ? request?.offset : 0;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Talkif.CampaignContactResponse, Talkif.CampaignContactListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                (response?.contacts ?? []).length > 0 &&
                (request?.limit == null || (response?.contacts ?? []).length >= request?.limit),
            getItems: (response) => response?.contacts ?? [],
            loadPage: (response) => {
                _offset += response?.contacts != null ? response.contacts.length : 1;
                return list(core.setObjectProperty(request, "offset", _offset));
            },
        });
    }

    /**
     * @param {Talkif.AddCampaignContactsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.addCampaignContacts({
     *         campaignId: "campaignId",
     *         contactIds: ["contactIds"]
     *     })
     */
    public addCampaignContacts(
        request: Talkif.AddCampaignContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.AddedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addCampaignContacts(request, requestOptions));
    }

    private async __addCampaignContacts(
        request: Talkif.AddCampaignContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.AddedResponse>> {
        const { campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/contacts`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.AddedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/contacts",
        );
    }

    /**
     * @param {Talkif.RemoveCampaignContactsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.removeCampaignContacts({
     *         campaignId: "campaignId",
     *         campaignContactIds: ["campaignContactIds"]
     *     })
     */
    public removeCampaignContacts(
        request: Talkif.RemoveCampaignContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.RemovedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__removeCampaignContacts(request, requestOptions));
    }

    private async __removeCampaignContacts(
        request: Talkif.RemoveCampaignContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.RemovedResponse>> {
        const { campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/contacts`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.RemovedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/campaigns/{campaignId}/contacts",
        );
    }

    /**
     * Bulk add contacts to a campaign using filter criteria.
     *
     * Instead of passing individual contact IDs, pass filter criteria:
     * - `tags`: Filter by contact tags (with `tagMode` for ANY/ALL matching)
     * - `company`: Filter by company name (exact match)
     * - `search`: Full-text search across name, company, occupation, email
     *
     * This allows adding thousands of contacts in a single request efficiently.
     *
     * @param {Talkif.BulkAddContactsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.bulkAddCampaignContacts({
     *         campaignId: "campaignId",
     *         filter: {}
     *     })
     */
    public bulkAddCampaignContacts(
        request: Talkif.BulkAddContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.BulkAddContactsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__bulkAddCampaignContacts(request, requestOptions));
    }

    private async __bulkAddCampaignContacts(
        request: Talkif.BulkAddContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.BulkAddContactsResponse>> {
        const { campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/contacts/bulk`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.BulkAddContactsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/contacts/bulk",
        );
    }

    /**
     * Bulk remove contacts from a campaign using the same filter criteria as bulk add.
     *
     * Contacts that already have a call record, or that are sitting in an active
     * queue slot, are never removed — the response reports `matched` and `removed`
     * separately so a partial removal is visible rather than silent.
     *
     * @param {Talkif.BulkRemoveContactsRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.bulkRemoveCampaignContacts({
     *         campaignId: "campaignId",
     *         filter: {}
     *     })
     */
    public bulkRemoveCampaignContacts(
        request: Talkif.BulkRemoveContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.BulkRemoveContactsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__bulkRemoveCampaignContacts(request, requestOptions));
    }

    private async __bulkRemoveCampaignContacts(
        request: Talkif.BulkRemoveContactsRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.BulkRemoveContactsResponse>> {
        const { campaignId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/contacts/bulk`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.BulkRemoveContactsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/campaigns/{campaignId}/contacts/bulk",
        );
    }

    /**
     * Mark a campaign contact as skipped (e.g., DNC, opt-out, manual skip).
     * The contact will be excluded from future claiming and calling.
     *
     * @param {Talkif.SkipContactRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.skipCampaignContact({
     *         campaignId: "campaignId",
     *         contactId: "contactId",
     *         reason: "manual"
     *     })
     */
    public skipCampaignContact(
        request: Talkif.SkipContactRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__skipCampaignContact(request, requestOptions));
    }

    private async __skipCampaignContact(
        request: Talkif.SkipContactRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId, contactId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/contacts/${core.url.encodePathParam(contactId)}/skip`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/contacts/{contactId}/skip",
        );
    }

    /**
     * Initiates the draining process for a running campaign:
     * - Status changes to Draining (stops feeding new contacts to queue)
     * - Active calls are allowed to complete naturally
     * - When active_calls_count reaches 0, status transitions to Paused
     *
     * @param {Talkif.PauseCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.UnprocessableEntityError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.pauseCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public pauseCampaign(
        request: Talkif.PauseCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__pauseCampaign(request, requestOptions));
    }

    private async __pauseCampaign(
        request: Talkif.PauseCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/pause`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Talkif.UnprocessableEntityError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/pause",
        );
    }

    /**
     * Restarts a campaign for non-called contacts. Resets failed/pending/not-called
     * contacts back to pending and starts the campaign from Paused/Completed/Cancelled state.
     *
     * @param {Talkif.RestartCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.UnprocessableEntityError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.restartCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public restartCampaign(
        request: Talkif.RestartCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__restartCampaign(request, requestOptions));
    }

    private async __restartCampaign(
        request: Talkif.RestartCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/restart`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Talkif.UnprocessableEntityError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/restart",
        );
    }

    /**
     * Resumes a paused campaign, transitioning it back to Running state.
     *
     * @param {Talkif.ResumeCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.UnprocessableEntityError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.resumeCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public resumeCampaign(
        request: Talkif.ResumeCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__resumeCampaign(request, requestOptions));
    }

    private async __resumeCampaign(
        request: Talkif.ResumeCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/resume`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Talkif.UnprocessableEntityError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/resume",
        );
    }

    /**
     * @param {Talkif.StartCampaignRequest} request
     * @param {CampaignsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.UnprocessableEntityError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.campaigns.startCampaign({
     *         campaignId: "campaignId"
     *     })
     */
    public startCampaign(
        request: Talkif.StartCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__startCampaign(request, requestOptions));
    }

    private async __startCampaign(
        request: Talkif.StartCampaignRequest,
        requestOptions?: CampaignsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { campaignId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/campaigns/${core.url.encodePathParam(campaignId)}/start`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Talkif.UnprocessableEntityError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/campaigns/{campaignId}/start",
        );
    }
}
