// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Talkif from "../../../index.js";

export declare namespace FlowsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Create and manage AI conversation flows
 */
export class FlowsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FlowsClient.Options>;

    constructor(options: FlowsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * GET /api/v1/flows
     *
     * Returns lightweight flow list with connected phones.
     *
     * @param {Talkif.ListFlowsRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.listFlows()
     */
    public listFlows(
        request: Talkif.ListFlowsRequest = {},
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.FlowListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listFlows(request, requestOptions));
    }

    private async __listFlows(
        request: Talkif.ListFlowsRequest = {},
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.FlowListResponse>> {
        const { limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/flows",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.FlowListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/flows");
    }

    /**
     * POST /api/v1/flows
     *
     * Definition is optional — omit to create an empty draft for the builder UI,
     * or provide it to create a flow with initial content.
     *
     * @param {Talkif.CreateFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.ConflictError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.createFlow({
     *         name: "Appointment Reminder"
     *     })
     */
    public createFlow(
        request: Talkif.CreateFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.FlowDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createFlow(request, requestOptions));
    }

    private async __createFlow(
        request: Talkif.CreateFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.FlowDetailResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/flows",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.FlowDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Talkif.ConflictError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/flows");
    }

    /**
     * GET /api/v1/flows/:flowId
     *
     * Returns full flow details including definition, layout, and connected phones.
     *
     * @param {Talkif.GetFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.getFlow({
     *         flowId: "flowId"
     *     })
     */
    public getFlow(
        request: Talkif.GetFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.FlowDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFlow(request, requestOptions));
    }

    private async __getFlow(
        request: Talkif.GetFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.FlowDetailResponse>> {
        const { flowId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.FlowDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/flows/{flowId}");
    }

    /**
     * PUT /api/v1/flows/:flowId
     *
     * @param {Talkif.UpdateFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.ConflictError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.updateFlow({
     *         flowId: "flowId"
     *     })
     */
    public updateFlow(
        request: Talkif.UpdateFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.FlowDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateFlow(request, requestOptions));
    }

    private async __updateFlow(
        request: Talkif.UpdateFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.FlowDetailResponse>> {
        const { flowId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.FlowDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Talkif.ConflictError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/v1/flows/{flowId}");
    }

    /**
     * DELETE /api/v1/flows/:flowId
     *
     * Returns 204 No Content on success.
     *
     * @param {Talkif.DeleteFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.deleteFlow({
     *         flowId: "flowId"
     *     })
     */
    public deleteFlow(
        request: Talkif.DeleteFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteFlow(request, requestOptions));
    }

    private async __deleteFlow(
        request: Talkif.DeleteFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { flowId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/v1/flows/{flowId}");
    }

    /**
     * POST /api/v1/flows/:flowId/publish
     *
     * @param {Talkif.PublishFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.ConflictError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.publishFlow({
     *         flowId: "flowId"
     *     })
     */
    public publishFlow(
        request: Talkif.PublishFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PublishFlowResponse> {
        return core.HttpResponsePromise.fromPromise(this.__publishFlow(request, requestOptions));
    }

    private async __publishFlow(
        request: Talkif.PublishFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PublishFlowResponse>> {
        const { flowId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}/publish`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PublishFlowResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Talkif.ConflictError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/flows/{flowId}/publish",
        );
    }

    /**
     * POST /api/v1/flows/:flowId/rollback/:version
     *
     * @param {Talkif.RollbackFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.ConflictError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.rollbackFlow({
     *         flowId: "flowId",
     *         version: "version"
     *     })
     */
    public rollbackFlow(
        request: Talkif.RollbackFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.RollbackResponse> {
        return core.HttpResponsePromise.fromPromise(this.__rollbackFlow(request, requestOptions));
    }

    private async __rollbackFlow(
        request: Talkif.RollbackFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.RollbackResponse>> {
        const { flowId, version } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}/rollback/${core.url.encodePathParam(version)}`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.RollbackResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Talkif.ConflictError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/flows/{flowId}/rollback/{version}",
        );
    }

    /**
     * POST /api/v1/flows/:flowId/validate
     *
     * @param {Talkif.ValidateFlowRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.validateFlow({
     *         flowId: "flowId"
     *     })
     */
    public validateFlow(
        request: Talkif.ValidateFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.ValidationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__validateFlow(request, requestOptions));
    }

    private async __validateFlow(
        request: Talkif.ValidateFlowRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.ValidationResponse>> {
        const { flowId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}/validate`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.ValidationResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/flows/{flowId}/validate",
        );
    }

    /**
     * GET /api/v1/flows/:flowId/versions/:version
     *
     * @param {Talkif.GetFlowVersionRequest} request
     * @param {FlowsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.flows.getFlowVersion({
     *         flowId: "flowId",
     *         version: "version"
     *     })
     */
    public getFlowVersion(
        request: Talkif.GetFlowVersionRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.FlowVersionDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFlowVersion(request, requestOptions));
    }

    private async __getFlowVersion(
        request: Talkif.GetFlowVersionRequest,
        requestOptions?: FlowsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.FlowVersionDetailResponse>> {
        const { flowId, version } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/flows/${core.url.encodePathParam(flowId)}/versions/${core.url.encodePathParam(version)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.FlowVersionDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/flows/{flowId}/versions/{version}",
        );
    }
}
