// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         format: "format"
 *     }
 */
export interface ExportContactsRequest {
    /** Export format: csv, json, or vcf */
    format: string;
}
