// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contactId: "contactId"
 *     }
 */
export interface GetContactRequest {
    /** Contact ID */
    contactId: string;
}
