// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         contactId: "contactId"
 *     }
 */
export interface UpdateContactRequest {
    /** Contact ID */
    contactId: string;
    address?: Talkif.ContactAddress | null;
    /** Company or organization name */
    company?: string | null;
    /** Email address */
    email?: string | null;
    /** Contact interests or topics (max 50) */
    interests?: string[] | null;
    /** BCP 47 language code (2-10 characters) */
    language?: string | null;
    /** Full name of the contact (1-255 characters) */
    name?: string | null;
    /** Free-text notes (max 5000 characters) */
    notes?: string | null;
    /** Job title or occupation */
    occupation?: string | null;
    /** Primary phone number in E.164 format */
    primaryPhone?: string | null;
    /** Additional phone numbers in E.164 format (max 10) */
    secondaryPhones?: string[] | null;
    /** Tags for categorization (max 50) */
    tags?: string[] | null;
    /** IANA timezone identifier */
    timezone?: string | null;
}
