// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AnalyticsClient", () => {
    test("get_campaign_analytics (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            attemptDistribution: [{ attempts: 1, contactCount: 350, percentage: 70 }],
            campaignId: "550e8400-e29b-41d4-a716-446655440000",
            costBreakdown: [
                {
                    category: "llm_conversation",
                    categoryDisplay: "LLM Conversation",
                    percentage: 32.7,
                    totalMicrocents: 150000000,
                    totalUsd: 1.1,
                },
            ],
            durationBuckets: [{ bucket: "bucket", count: 1000000, percentage: 1.1 }],
            failureCauses: [{ code: "code", count: 1000000, example: "example", label: "label", percentage: 1.1 }],
            hourlyVolume: [{ callCount: 15, completed: 12, failed: 2, timestamp: "2026-01-15T09:00:00Z" }],
            outcomes: [{ count: 320, outcome: "completed", percentage: 64 }],
            overview: {
                avgDurationSeconds: 120,
                completed: 320,
                failed: 30,
                noAnswer: 40,
                skipped: 10,
                successRate: 80,
                totalCalls: 400,
                totalCost: "45.80",
                totalDurationSeconds: 48000,
            },
            performance: {
                callsAnalyzed: 320,
                conversation: {
                    avgBotSpeechSecs: 68.7,
                    avgInterruptionRate: 0.15,
                    avgTalkRatio: 0.38,
                    avgTurns: 8.5,
                    avgUserSpeechSecs: 42.3,
                },
                functionCalls: {
                    avgDurationMs: 450,
                    avgPerCall: 4,
                    callsWithFunctions: 85,
                    totalCalls: 340,
                    totalDurationMs: 153000,
                },
                latency: { avgFirstSpeechMs: 1150, p50FirstSpeechMs: 980, p95FirstSpeechMs: 2100 },
                usage: {
                    avgCompletionTokens: 517,
                    avgPromptTokens: 2042,
                    avgTtsCharacters: 3167,
                    totalCompletionTokens: 62000,
                    totalPromptTokens: 245000,
                    totalTtsCharacters: 380000,
                },
            },
            voicemail: { human: 1000000, undetermined: 1000000, voicemail: 1000000, voicemailRate: 1.1 },
        };

        server
            .mockEndpoint()
            .get("/api/v1/campaigns/campaignId/analytics")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.analytics.getCampaignAnalytics({
            campaignId: "campaignId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_campaign_analytics (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/campaigns/campaignId/analytics")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getCampaignAnalytics({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_campaign_analytics (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/campaigns/campaignId/analytics")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getCampaignAnalytics({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_campaign_analytics (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/campaigns/campaignId/analytics")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getCampaignAnalytics({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_campaign_analytics (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/campaigns/campaignId/analytics")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getCampaignAnalytics({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_campaign_analytics (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/campaigns/campaignId/analytics")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getCampaignAnalytics({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_flow_stats (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            calls: { completed: 120, failed: 10, inProgress: 5, noAnswer: 15, total: 150 },
            costs: { average: "$0.08", total: "$12.50" },
            direction: { inbound: 60, outbound: 90 },
            duration: { averageSeconds: 120, totalSeconds: 18000 },
            endDate: "2026-01-16T00:00:00Z",
            flowId: "550e8400-e29b-41d4-a716-446655440000",
            flowName: "Appointment Reminder",
            period: "today",
            rates: { failureRate: 14.5, successRate: 85.5 },
            startDate: "2026-01-15T00:00:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/flows/flowId/stats")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.analytics.getFlowStats({
            flowId: "flowId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_flow_stats (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flows/flowId/stats")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getFlowStats({
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_flow_stats (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flows/flowId/stats")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getFlowStats({
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_flow_stats (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flows/flowId/stats")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getFlowStats({
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_flow_stats (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flows/flowId/stats")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getFlowStats({
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_flow_stats (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flows/flowId/stats")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analytics.getFlowStats({
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });
});
