// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BillingClient", () => {
    test("get_balance_summary (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            available: "125.50",
            bonusBalance: "25.50",
            earliestExpiration: "2024-01-15T09:30:00Z",
            purchasedBalance: "100.00",
        };

        server
            .mockEndpoint()
            .get("/api/v1/billing/balance")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getBalanceSummary();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_balance_summary (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/balance")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBalanceSummary();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_balance_summary (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/balance")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBalanceSummary();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_balance_summary (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/balance")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBalanceSummary();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_balance_summary (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/balance")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBalanceSummary();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("list_charges (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { meta: { limit: 20, offset: 0, total: 142 } };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.listCharges();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_charges (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listCharges();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_charges (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listCharges();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_charges (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listCharges();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_charges (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listCharges();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_charge_detail (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            chargeType: "call_usage",
            chargeTypeDisplay: "Call Usage",
            contactName: "Jane Smith",
            createdAt: "2026-01-15T10:30:00Z",
            description: "Call to Jane Smith via +15551234567",
            failureCode: "failureCode",
            failureReason: "failureReason",
            flowName: "Sales Flow",
            icon: "phone",
            id: "550e8400-e29b-41d4-a716-446655440000",
            lineItems: [
                {
                    amountUsd: 1.1,
                    billableId: "660e8400-e29b-41d4-a716-446655440000",
                    billableType: "call",
                    category: "llm_conversation",
                    categoryDisplay: "LLM Conversation",
                    createdAt: "2026-01-15T10:30:00Z",
                    id: "550e8400-e29b-41d4-a716-446655440000",
                    rateMicrocents: 15000,
                    rateUnit: "per_1k_tokens",
                    usageData: { key: "value" },
                    usageQuantity: 1500,
                    usageUnit: "tokens",
                },
            ],
            phoneNumber: "+15551234567",
            referenceId: "550e8400-e29b-41d4-a716-446655440000",
            referenceType: "call",
            refundedMicrocents: 0,
            status: "pending",
            statusDisplay: "Completed",
            subtotalMicrocents: 50000,
            taxMicrocents: 0,
            totalMicrocents: 50000,
            totalUsd: 1.1,
        };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges/chargeId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getChargeDetail({
            chargeId: "chargeId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_charge_detail (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges/chargeId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getChargeDetail({
                chargeId: "chargeId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_charge_detail (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges/chargeId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getChargeDetail({
                chargeId: "chargeId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_charge_detail (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges/chargeId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getChargeDetail({
                chargeId: "chargeId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_charge_detail (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges/chargeId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getChargeDetail({
                chargeId: "chargeId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_charge_detail (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/charges/chargeId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getChargeDetail({
                chargeId: "chargeId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_billing_cost_breakdown (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            byCategory: [
                {
                    category: "llm_conversation",
                    categoryDisplay: "LLM Conversation",
                    percentage: 32.7,
                    totalMicrocents: 150000000,
                    totalUsd: 1.1,
                },
            ],
            byFlow: [
                {
                    flowId: "550e8400-e29b-41d4-a716-446655440000",
                    flowName: "flowName",
                    totalMicrocents: 82000000,
                    totalUsd: 1.1,
                },
            ],
            calls: [
                {
                    byCategory: [
                        {
                            category: "llm_conversation",
                            categoryDisplay: "LLM Conversation",
                            percentage: 32.7,
                            totalMicrocents: 150000000,
                            totalUsd: 1.1,
                        },
                    ],
                    callId: "550e8400-e29b-41d4-a716-446655440000",
                    contactId: "contactId",
                    createdAt: "2026-01-15T10:30:00Z",
                    direction: "direction",
                    durationSeconds: 1,
                    flowId: "flowId",
                    flowName: "flowName",
                    totalMicrocents: 5000000,
                    totalUsd: 1.1,
                },
            ],
            endDate: "2026-01-16T00:00:00Z",
            period: "week",
            startDate: "2026-01-09T00:00:00Z",
            totalMicrocents: 458000000,
            totalUsd: 1.1,
        };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getBillingCostBreakdown();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_billing_cost_breakdown (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCostBreakdown();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_billing_cost_breakdown (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCostBreakdown();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_billing_cost_breakdown (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCostBreakdown();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_billing_cost_breakdown (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCostBreakdown();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_billing_call_cost_breakdown (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            callId: "550e8400-e29b-41d4-a716-446655440000",
            lineItems: [
                {
                    amountMicrocents: 2500000,
                    amountUsd: 1.1,
                    category: "llm_conversation",
                    categoryDisplay: "LLM Conversation",
                    createdAt: "2026-01-15T10:30:00Z",
                    id: "550e8400-e29b-41d4-a716-446655440000",
                    rateMicrocents: 1000000,
                    rateUnit: "rateUnit",
                    usageData: { key: "value" },
                    usageQuantity: 1000000,
                    usageUnit: "usageUnit",
                },
            ],
            totalMicrocents: 5000000,
            totalUsd: 1.1,
        };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs/calls/callId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getBillingCallCostBreakdown({
            callId: "callId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_billing_call_cost_breakdown (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs/calls/callId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCallCostBreakdown({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_billing_call_cost_breakdown (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs/calls/callId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCallCostBreakdown({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_billing_call_cost_breakdown (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs/calls/callId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCallCostBreakdown({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_billing_call_cost_breakdown (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs/calls/callId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCallCostBreakdown({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_billing_call_cost_breakdown (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/costs/calls/callId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getBillingCallCostBreakdown({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("list_invoices (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { meta: { limit: 20, offset: 0, total: 142 } };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.listInvoices();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_invoices (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listInvoices();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_invoices (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listInvoices();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_invoices (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listInvoices();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_invoices (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.listInvoices();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_invoice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            amountDue: 5000,
            amountPaid: 5000,
            billingReason: "subscription_cycle",
            createdAt: "2026-01-15T10:30:00Z",
            currency: "usd",
            dueDate: "2026-02-01T00:00:00Z",
            hostedInvoiceUrl: "https://invoice.stripe.com/i/acct_1234/inv_5678",
            id: "550e8400-e29b-41d4-a716-446655440000",
            invoicePdfUrl: "https://pay.stripe.com/invoice/acct_1234/inv_5678/pdf",
            paidAt: "2026-01-15T10:35:00Z",
            periodEnd: "2026-02-01T00:00:00Z",
            periodStart: "2026-01-01T00:00:00Z",
            status: "draft",
            stripeInvoiceId: "in_1NVChN2eZvKYlo2CrbkAlkmh",
        };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices/invoiceId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getInvoice({
            invoiceId: "invoiceId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_invoice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices/invoiceId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getInvoice({
                invoiceId: "invoiceId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_invoice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices/invoiceId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getInvoice({
                invoiceId: "invoiceId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_invoice (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices/invoiceId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getInvoice({
                invoiceId: "invoiceId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_invoice (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices/invoiceId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getInvoice({
                invoiceId: "invoiceId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_invoice (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/invoices/invoiceId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getInvoice({
                invoiceId: "invoiceId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_transaction_history (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { meta: { limit: 20, offset: 0, total: 142 } };

        server
            .mockEndpoint()
            .get("/api/v1/billing/transactions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.getTransactionHistory();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_transaction_history (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/transactions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getTransactionHistory();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_transaction_history (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/transactions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getTransactionHistory();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_transaction_history (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/transactions")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getTransactionHistory();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_transaction_history (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/billing/transactions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.getTransactionHistory();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_public_pricing", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            phoneNumbers: {
                note: "Monthly cost varies by country and number type. Price shown is for US local numbers.",
                startingFrom: { display: "$0.0140", microcents: 14000 },
            },
            recordingStorage: {
                note: "Billed based on actual storage duration. Minimum 1 day charged.",
                perGbMonth: { display: "$0.0140", microcents: 14000 },
            },
            telephony: [
                { model: "model", provider: "twilio", rates: { key: { display: "$0.0140", microcents: 14000 } } },
            ],
        };

        server.mockEndpoint().get("/api/v1/pricing").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.billing.getPublicPricing();
        expect(response).toEqual(rawResponseBody);
    });
});
