// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContactsClient", () => {
    test("list_contacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            contacts: [
                {
                    accountId: "550e8400-e29b-41d4-a716-446655440000",
                    address: { key: "value" },
                    company: "Acme Corp",
                    createdAt: "2026-01-15T10:30:00Z",
                    deletedAt: "2024-01-15T09:30:00Z",
                    email: "jane@example.com",
                    id: "550e8400-e29b-41d4-a716-446655440000",
                    interests: ["healthcare", "scheduling"],
                    language: "en",
                    lastContactedAt: "2024-01-15T09:30:00Z",
                    name: "Jane Smith",
                    notes: "notes",
                    occupation: "Product Manager",
                    primaryPhone: "+15551234567",
                    secondaryPhones: ["+15559876543", "+15558765432"],
                    tags: ["vip", "priority"],
                    timezone: "America/New_York",
                    updatedAt: "2026-01-15T10:30:00Z",
                },
            ],
            meta: { limit: 20, offset: 0, total: 142 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/api/v1/contacts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.contacts.listContacts();

        expect(expected.contacts).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.contacts).toEqual(nextPage.data);
    });

    test("list_contacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/contacts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_contacts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/contacts").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_contacts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/contacts").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_contacts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/contacts").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.listContacts();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("create_contact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Jane Smith", primaryPhone: "+15551234567" };
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            address: { key: "value" },
            company: "Acme Corp",
            createdAt: "2026-01-15T10:30:00Z",
            deletedAt: "2024-01-15T09:30:00Z",
            email: "jane@example.com",
            id: "550e8400-e29b-41d4-a716-446655440000",
            interests: ["healthcare", "scheduling"],
            language: "en",
            lastContactedAt: "2024-01-15T09:30:00Z",
            name: "Jane Smith",
            notes: "notes",
            occupation: "Product Manager",
            primaryPhone: "+15551234567",
            secondaryPhones: ["+15559876543", "+15558765432"],
            tags: ["vip", "priority"],
            timezone: "America/New_York",
            updatedAt: "2026-01-15T10:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.createContact({
            name: "Jane Smith",
            primaryPhone: "+15551234567",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_contact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", primaryPhone: "primaryPhone" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                name: "name",
                primaryPhone: "primaryPhone",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("create_contact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", primaryPhone: "primaryPhone" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                name: "name",
                primaryPhone: "primaryPhone",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("create_contact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", primaryPhone: "primaryPhone" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                name: "name",
                primaryPhone: "primaryPhone",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("create_contact (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", primaryPhone: "primaryPhone" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                name: "name",
                primaryPhone: "primaryPhone",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("create_contact (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", primaryPhone: "primaryPhone" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.createContact({
                name: "name",
                primaryPhone: "primaryPhone",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("export_contacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/api/v1/contacts/export").respondWith().statusCode(200).build();

        const response = await client.contacts.exportContacts({
            format: "format",
        });
        expect(response).toEqual(undefined);
    });

    test("export_contacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/export")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.exportContacts({
                format: "format",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("export_contacts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/export")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.exportContacts({
                format: "format",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("export_contacts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/export")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.exportContacts({
                format: "format",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("export_contacts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/export")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.exportContacts({
                format: "format",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("export_contacts (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/export")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.exportContacts({
                format: "format",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("import_contacts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileContent: "Sm9obiBEb2UsKzE1NTUxMjM0NTY3", format: "vcf" };
        const rawResponseBody = {
            errors: [
                {
                    contactName: "Jane Smith",
                    message: "Invalid phone format: 555-1234. Must be E.164 format (e.g., +15551234567)",
                    phone: "+15551234567",
                    reason: "INVALID_PHONE_FORMAT",
                    row: 7,
                },
            ],
            failed: 15,
            imported: 120,
            preview: [
                {
                    company: "Acme Corp",
                    email: "jane@example.com",
                    interests: ["healthcare", "scheduling"],
                    language: "en",
                    name: "Jane Smith",
                    notes: "notes",
                    occupation: "Product Manager",
                    primaryPhone: "+15551234567",
                    secondaryPhones: ["+15559876543"],
                    tags: ["vip", "priority"],
                    timezone: "America/New_York",
                },
            ],
            skipped: 15,
            skippedPreview: [
                { name: "Jane Smith", phone: "+15551234567", reason: "Duplicate phone number already exists", row: 3 },
            ],
            totalRows: 150,
        };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.importContacts({
            fileContent: "Sm9obiBEb2UsKzE1NTUxMjM0NTY3",
            format: "vcf",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("import_contacts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileContent: "fileContent", format: "vcf" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.importContacts({
                fileContent: "fileContent",
                format: "vcf",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("import_contacts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileContent: "fileContent", format: "vcf" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.importContacts({
                fileContent: "fileContent",
                format: "vcf",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("import_contacts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileContent: "fileContent", format: "vcf" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.importContacts({
                fileContent: "fileContent",
                format: "vcf",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("import_contacts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileContent: "fileContent", format: "vcf" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.importContacts({
                fileContent: "fileContent",
                format: "vcf",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("import_contacts (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileContent: "fileContent", format: "vcf" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.importContacts({
                fileContent: "fileContent",
                format: "vcf",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("search_by_phone (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            contact: {
                accountId: "550e8400-e29b-41d4-a716-446655440000",
                address: { key: "value" },
                company: "Acme Corp",
                createdAt: "2026-01-15T10:30:00Z",
                deletedAt: "2024-01-15T09:30:00Z",
                email: "jane@example.com",
                id: "550e8400-e29b-41d4-a716-446655440000",
                interests: ["healthcare", "scheduling"],
                language: "en",
                lastContactedAt: "2024-01-15T09:30:00Z",
                name: "Jane Smith",
                notes: "notes",
                occupation: "Product Manager",
                primaryPhone: "+15551234567",
                secondaryPhones: ["+15559876543", "+15558765432"],
                tags: ["vip", "priority"],
                timezone: "America/New_York",
                updatedAt: "2026-01-15T10:30:00Z",
            },
            matchedPhone: "+15551234567",
        };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/search/phone/phone")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.searchByPhone({
            phone: "phone",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("search_by_phone (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/search/phone/phone")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.searchByPhone({
                phone: "phone",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("search_by_phone (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/search/phone/phone")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.searchByPhone({
                phone: "phone",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("search_by_phone (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/search/phone/phone")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.searchByPhone({
                phone: "phone",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("search_by_phone (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/search/phone/phone")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.searchByPhone({
                phone: "phone",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("list_tags (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { tags: [{ count: 23, name: "vip" }] };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/tags")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.listTags();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_tags (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/tags")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.listTags();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_tags (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/tags")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.listTags();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_tags (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/tags")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.listTags();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_tags (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/tags")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.listTags();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_contact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            address: { key: "value" },
            company: "Acme Corp",
            createdAt: "2026-01-15T10:30:00Z",
            deletedAt: "2024-01-15T09:30:00Z",
            email: "jane@example.com",
            id: "550e8400-e29b-41d4-a716-446655440000",
            interests: ["healthcare", "scheduling"],
            language: "en",
            lastContactedAt: "2024-01-15T09:30:00Z",
            name: "Jane Smith",
            notes: "notes",
            occupation: "Product Manager",
            primaryPhone: "+15551234567",
            secondaryPhones: ["+15559876543", "+15558765432"],
            tags: ["vip", "priority"],
            timezone: "America/New_York",
            updatedAt: "2026-01-15T10:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.getContact({
            contactId: "contactId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_contact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_contact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_contact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_contact (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_contact (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("update_contact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            address: { key: "value" },
            company: "Acme Corp",
            createdAt: "2026-01-15T10:30:00Z",
            deletedAt: "2024-01-15T09:30:00Z",
            email: "jane@example.com",
            id: "550e8400-e29b-41d4-a716-446655440000",
            interests: ["healthcare", "scheduling"],
            language: "en",
            lastContactedAt: "2024-01-15T09:30:00Z",
            name: "Jane Smith",
            notes: "notes",
            occupation: "Product Manager",
            primaryPhone: "+15551234567",
            secondaryPhones: ["+15559876543", "+15558765432"],
            tags: ["vip", "priority"],
            timezone: "America/New_York",
            updatedAt: "2026-01-15T10:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.updateContact({
            contactId: "contactId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_contact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("update_contact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("update_contact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("update_contact (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("update_contact (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("update_contact (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/contacts/contactId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.updateContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("delete_contact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/contacts/contactId").respondWith().statusCode(200).build();

        const response = await client.contacts.deleteContact({
            contactId: "contactId",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_contact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("delete_contact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("delete_contact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("delete_contact (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("delete_contact (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.deleteContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_contact_calls (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            calls: [
                {
                    accountId: "550e8400-e29b-41d4-a716-446655440000",
                    agentConnectedAt: "2024-01-15T09:30:00Z",
                    agentDisconnectedAt: "2024-01-15T09:30:00Z",
                    agentStatus: "pending",
                    botSpeechSecs: 78.2,
                    callSid: "CA1234567890abcdef1234567890abcdef",
                    campaignId: "campaignId",
                    completionTokens: 512,
                    contact: {
                        company: "Acme Corp",
                        id: "550e8400-e29b-41d4-a716-446655440000",
                        name: "Jane Smith",
                        tags: ["vip", "priority"],
                    },
                    cost: "0.053200",
                    createdAt: "2026-01-15T10:30:00Z",
                    dataRetainedAt: "2024-01-15T09:30:00Z",
                    direction: "inbound",
                    duration: 125,
                    endReason: "caller_hangup",
                    endedAt: "2024-01-15T09:30:00Z",
                    failureCode: "capacity_limit",
                    failureReason: "Recipient did not answer",
                    firstSpeechMs: 1250,
                    flowId: "flowId",
                    fromNumber: "+15559876543",
                    functionCallCount: 3,
                    functionCallTotalMs: 1730,
                    id: "550e8400-e29b-41d4-a716-446655440000",
                    interruptedTurns: 2,
                    isAnalyzed: true,
                    isLead: true,
                    isRecorded: true,
                    promptTokens: 2048,
                    providerType: "twilio",
                    queueInfo: {
                        attemptCount: 0,
                        estimatedWaitSeconds: 30,
                        position: 3,
                        queueId: "550e8400-e29b-41d4-a716-446655440000",
                        queuedAt: "2026-01-15T10:30:00Z",
                        status: "pending",
                    },
                    recordingDurationSecs: 120.5,
                    recordingExpiresAt: "2024-01-15T09:30:00Z",
                    recordingFileSizeBytes: 1048576,
                    recordingStatus: "ready",
                    recordingStorageCost: "0.000150",
                    scheduleId: "scheduleId",
                    source: "direct",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "queued",
                    telephonyStatus: "initiating",
                    toNumber: "+15551234567",
                    triggerDetail: "Spring promo form",
                    ttsCharacters: 3200,
                    turnCount: 12,
                    userSpeechSecs: 45.5,
                    voicemailDetectedAt: "2024-01-15T09:30:00Z",
                    voicemailStatus: "voicemail_detected",
                },
            ],
            meta: { limit: 20, offset: 0, total: 142 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/api/v1/contacts/contactId/calls")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.contacts.getContactCalls({
            contactId: "contactId",
        });

        expect(expected.calls).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.calls).toEqual(nextPage.data);
    });

    test("get_contact_calls (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId/calls")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactCalls({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_contact_calls (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId/calls")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactCalls({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_contact_calls (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId/calls")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactCalls({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_contact_calls (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId/calls")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactCalls({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_contact_calls (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/contacts/contactId/calls")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.getContactCalls({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("restore_contact (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            address: { key: "value" },
            company: "Acme Corp",
            createdAt: "2026-01-15T10:30:00Z",
            deletedAt: "2024-01-15T09:30:00Z",
            email: "jane@example.com",
            id: "550e8400-e29b-41d4-a716-446655440000",
            interests: ["healthcare", "scheduling"],
            language: "en",
            lastContactedAt: "2024-01-15T09:30:00Z",
            name: "Jane Smith",
            notes: "notes",
            occupation: "Product Manager",
            primaryPhone: "+15551234567",
            secondaryPhones: ["+15559876543", "+15558765432"],
            tags: ["vip", "priority"],
            timezone: "America/New_York",
            updatedAt: "2026-01-15T10:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/restore")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.restoreContact({
            contactId: "contactId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("restore_contact (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/restore")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.restoreContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("restore_contact (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/restore")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.restoreContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("restore_contact (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/restore")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.restoreContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("restore_contact (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/restore")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.restoreContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("restore_contact (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/restore")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.restoreContact({
                contactId: "contactId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("add_tags (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["vip", "priority"] };
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            address: { key: "value" },
            company: "Acme Corp",
            createdAt: "2026-01-15T10:30:00Z",
            deletedAt: "2024-01-15T09:30:00Z",
            email: "jane@example.com",
            id: "550e8400-e29b-41d4-a716-446655440000",
            interests: ["healthcare", "scheduling"],
            language: "en",
            lastContactedAt: "2024-01-15T09:30:00Z",
            name: "Jane Smith",
            notes: "notes",
            occupation: "Product Manager",
            primaryPhone: "+15551234567",
            secondaryPhones: ["+15559876543", "+15558765432"],
            tags: ["vip", "priority"],
            timezone: "America/New_York",
            updatedAt: "2026-01-15T10:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.addTags({
            contactId: "contactId",
            tags: ["vip", "priority"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("add_tags (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("add_tags (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("add_tags (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("add_tags (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("add_tags (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("add_tags (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.addTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("remove_tags (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["vip"] };
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            address: { key: "value" },
            company: "Acme Corp",
            createdAt: "2026-01-15T10:30:00Z",
            deletedAt: "2024-01-15T09:30:00Z",
            email: "jane@example.com",
            id: "550e8400-e29b-41d4-a716-446655440000",
            interests: ["healthcare", "scheduling"],
            language: "en",
            lastContactedAt: "2024-01-15T09:30:00Z",
            name: "Jane Smith",
            notes: "notes",
            occupation: "Product Manager",
            primaryPhone: "+15551234567",
            secondaryPhones: ["+15559876543", "+15558765432"],
            tags: ["vip", "priority"],
            timezone: "America/New_York",
            updatedAt: "2026-01-15T10:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.removeTags({
            contactId: "contactId",
            tags: ["vip"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("remove_tags (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("remove_tags (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("remove_tags (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("remove_tags (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("remove_tags (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("remove_tags (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { tags: ["tags", "tags"] };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/contacts/contactId/tags")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.removeTags({
                contactId: "contactId",
                tags: ["tags", "tags"],
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });
});
