// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FlowFunctionsClient", () => {
    test("list_flow_functions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { meta: { limit: 20, offset: 0, total: 142 } };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flowFunctions.listFlowFunctions();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_flow_functions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.listFlowFunctions();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_flow_functions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.listFlowFunctions();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_flow_functions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.listFlowFunctions();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_flow_functions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.listFlowFunctions();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("create_flow_function (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            description: "Create a new customer order",
            name: "create_order",
            request: { method: "POST", url: "https://api.example.com/orders/{orderId}" },
        };
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            createdAt: "2026-01-15T10:30:00Z",
            description: "Create a new customer order",
            hasWebhookHeaders: true,
            id: "550e8400-e29b-41d4-a716-446655440000",
            isActive: true,
            name: "create_order",
            paramBindings: { key: "value" },
            request: {
                body: { key: "value" },
                method: "POST",
                pathParams: { key: "value" },
                queryParams: { key: "value" },
                url: "https://api.example.com/orders/{orderId}",
            },
            slug: "create-order",
            timeoutMs: 5000,
            updatedAt: "2026-01-20T14:00:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flowFunctions.createFlowFunction({
            description: "Create a new customer order",
            name: "create_order",
            request: {
                method: "POST",
                url: "https://api.example.com/orders/{orderId}",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_flow_function (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { description: "description", name: "name", request: { method: "method", url: "url" } };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.createFlowFunction({
                description: "description",
                name: "name",
                request: {
                    method: "method",
                    url: "url",
                },
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("create_flow_function (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { description: "description", name: "name", request: { method: "method", url: "url" } };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.createFlowFunction({
                description: "description",
                name: "name",
                request: {
                    method: "method",
                    url: "url",
                },
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("create_flow_function (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { description: "description", name: "name", request: { method: "method", url: "url" } };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.createFlowFunction({
                description: "description",
                name: "name",
                request: {
                    method: "method",
                    url: "url",
                },
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("create_flow_function (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { description: "description", name: "name", request: { method: "method", url: "url" } };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.createFlowFunction({
                description: "description",
                name: "name",
                request: {
                    method: "method",
                    url: "url",
                },
            });
        }).rejects.toThrow(Talkif.ConflictError);
    });

    test("create_flow_function (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { description: "description", name: "name", request: { method: "method", url: "url" } };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.createFlowFunction({
                description: "description",
                name: "name",
                request: {
                    method: "method",
                    url: "url",
                },
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("create_flow_function (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { description: "description", name: "name", request: { method: "method", url: "url" } };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/flow-functions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.createFlowFunction({
                description: "description",
                name: "name",
                request: {
                    method: "method",
                    url: "url",
                },
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_flow_function (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            createdAt: "2026-01-15T10:30:00Z",
            description: "Create a new customer order",
            hasWebhookHeaders: true,
            id: "550e8400-e29b-41d4-a716-446655440000",
            isActive: true,
            name: "create_order",
            paramBindings: { key: "value" },
            request: {
                body: { key: "value" },
                method: "POST",
                pathParams: { key: "value" },
                queryParams: { key: "value" },
                url: "https://api.example.com/orders/{orderId}",
            },
            slug: "create-order",
            timeoutMs: 5000,
            updatedAt: "2026-01-20T14:00:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flowFunctions.getFlowFunction({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_flow_function (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.getFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_flow_function (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.getFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_flow_function (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.getFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_flow_function (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.getFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_flow_function (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.getFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("update_flow_function (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            createdAt: "2026-01-15T10:30:00Z",
            description: "Create a new customer order",
            hasWebhookHeaders: true,
            id: "550e8400-e29b-41d4-a716-446655440000",
            isActive: true,
            name: "create_order",
            paramBindings: { key: "value" },
            request: {
                body: { key: "value" },
                method: "POST",
                pathParams: { key: "value" },
                queryParams: { key: "value" },
                url: "https://api.example.com/orders/{orderId}",
            },
            slug: "create-order",
            timeoutMs: 5000,
            updatedAt: "2026-01-20T14:00:00Z",
        };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flowFunctions.updateFlowFunction({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_flow_function (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.updateFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("update_flow_function (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.updateFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("update_flow_function (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.updateFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("update_flow_function (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.updateFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("update_flow_function (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.updateFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("update_flow_function (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/flow-functions/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.updateFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("delete_flow_function (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/flow-functions/id").respondWith().statusCode(200).build();

        const response = await client.flowFunctions.deleteFlowFunction({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_flow_function (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.deleteFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("delete_flow_function (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.deleteFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("delete_flow_function (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.deleteFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("delete_flow_function (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.deleteFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("delete_flow_function (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/flow-functions/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flowFunctions.deleteFlowFunction({
                id: "id",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });
});
