// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         description: "Create a new customer order",
 *         name: "create_order",
 *         request: {
 *             method: "POST",
 *             url: "https://api.example.com/orders/{orderId}"
 *         }
 *     }
 */
export interface CreateFlowFunctionRequest {
    /** Description of what the function does (1-1000 characters) */
    description: string;
    /** Display name (1-255 characters) */
    name: string;
    /**
     * Per-parameter source bindings keyed by flat param name. Optional —
     * defaults to empty `{}` (all parameters are LLM-extracted). Keys must
     * match a property name in `request.pathParams`, `request.queryParams`,
     * or `request.body`. Values:
     * - `{ "source": "llm" }` — LLM extracts from conversation
     * - `{ "source": "call_context", "contextKey": "caller.contact_id", "onNull": "reject" }`
     * - `{ "source": "static", "value": "2026-01" }`
     */
    paramBindings?: Record<string, unknown> | null;
    /**
     * Structured HTTP request: method, url, pathParams, queryParams, body.
     * See [`RequestSchema`] for shape.
     */
    request: Talkif.RequestSchema;
    /** Timeout in milliseconds (100-30000) */
    timeoutMs?: number;
    /** Headers to send with the webhook (encrypted at rest). Write-only. */
    webhookHeaders?: Record<string, unknown> | null;
}
