// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateFlowFunctionRequest {
    id: string;
    /** Updated description (1-1000 characters) */
    description?: string | null;
    /** Updated active status */
    isActive?: boolean | null;
    /** Updated display name (1-255 characters) */
    name?: string | null;
    /**
     * Updated per-parameter bindings. Omit to keep existing; `{}` to clear to
     * all-LLM behavior; object to replace.
     */
    paramBindings?: Record<string, unknown> | null;
    request?: Talkif.RequestSchema | null;
    /** Updated timeout in milliseconds (100-30000) */
    timeoutMs?: number | null;
    /** Updated headers (encrypted at rest). Pass null to clear, omit to keep existing. */
    webhookHeaders?: Record<string, unknown> | null;
}
